### ISSUE TITLE
当日配布するタイムスケジュールの紙作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#100]
must書くもの
- [x] タイムスケジュール
- [x] スポンサーロゴ
- [x] 注意事項(飲食について、など)
  - [x] ランチマップをQRコードでつける
- [x] カンファレンスページQRコード
- [ ](場所があれば) セッション概要

**Comment by Gyori** [comment]
たたき
https://drive.google.com/file/d/0B0Vs20dDhCZmYkpzRXhhNkVoOUk/view?usp=sharing

片面だと入り切らなそう。。。

**Comment by okohs** [comment]
作り雑だけど片面で作ってみた
![gwjp2016 _](https://cloud.githubusercontent.com/assets/10089070/19362955/86c21938-91c3-11e6-8aaa-5a3a75e2a21c.png)

**Comment by mahya8585** [comment]
縦にして３分割
(HPと同じ要領)

A4縦

間に合えばプリントパック
間に合わなければキンコーズ

**Comment by okohs** [comment]
施設用画像
http://nyc.niye.go.jp/category/facilities/center/

**Comment by okohs** [comment]
【状況報告】仕掛中です。誰か印刷業者とか探してほしい・・・

**Comment by mahya8585** [comment]
http://www.printpac.co.jp/pricelist/list.php?product=leaflet&size=4&paper_type=1&paper=1&noki=7_6&changed=&proceed=on

**Comment by kanakogohzu** [comment]
仕事ではいつもここ利用しています。安い＆お急ぎ便がある＆supportの反応が早い。
http://www.tcpc.co.jp/

**Comment by Gyori** [comment]
私もプリントパック使うこと多いです。
http://www.printpac.co.jp

**Comment by okoysm** [comment]
![Uploading gwjp2016チラシ1014.png…]()

**Comment by okohs** [comment]
チラシできた

**Comment by okohs** [comment]
直した
https://drive.google.com/drive/u/0/folders/0B0Vs20dDhCZmS0o0V0pLcEJJSTA

**Comment by okohs** [comment]
あと印刷。みほさんサポート

**Comment by okohs** [comment]
![gwjp2016 _fix](https://cloud.githubusercontent.com/assets/10089070/19851621/2a54aa8e-9fa2-11e6-9e56-f2f217389d7b.png)

**Comment by okohs** [comment]
アンケート追加&Happyデジタル追加
![gwjp2016 _fix](https://cloud.githubusercontent.com/assets/10089070/19852042/59d5bc92-9fa4-11e6-8400-9d1fc63f5b99.png)

**Comment by okohs** [comment]
![gwjp2016 1014](https://cloud.githubusercontent.com/assets/10089070/19852182/2f85abd6-9fa5-11e6-9e71-73b66f408829.png)

**Comment by okohs** [comment]
申し込み＆入稿done
