### ISSUE TITLE
スポンサーにメール

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#101]
- [x] 登録してね
- [x] 一般でいいよ
- [x] 納金予定日確認

**Comment by okohs** [comment]
@mahya8585 まだメールしていなかったら以下の企業にロゴはよ、って急かして欲しい（せっかくスポンサーしていただいているのにHPに掲載できない・・・
- GitHub
- ハッピーコム（Happyデジタル）
- focusrite

**Comment by mahya8585** [comment]
ロゴもくれのメールしておいた（見てくれるかはわからん
