### ISSUE TITLE
スポンサーLTの時間を記載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#102]
closing内でスポンサーLTをやりたいと思います。
スポンサーLTは2枠を予定しています。
それ以上増える場合はopeningに2枠追加したいと思います。

というわけで、とりあえずclosingにスポンサーLTの文字の追加をお願いします><!

HP: @okoysm

**Comment by Gyori** [comment]
dotsの編集しかわからず・・ @okoysm すみません、お願いしまするmm

**Comment by okohs** [comment]
done
