### ISSUE TITLE
GitHub 請求書再作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#106]
@kanakogohzu お手数ですが再作成よろしくお願いします
- 住所を本社宛に(mailで住所が送られてきています。件名「Geek Women Japan 2016 sponsored procedure」の最新のメールをご確認ください）
- 宛名から担当者名を削除

**Comment by kanakogohzu** [comment]
@mahya8585 差し替えてドライブにアップしなおしてきました〜 🙏

**Comment by mahya8585** [comment]
あざます！確認の上送付してきます！

**Comment by mahya8585** [comment]
@kanakogohzu 宛名にGitHub Inc.と入れていただけますか！
忙しいようであれば原本アップしてもらえれば私のほうでやりますー

**Comment by kanakogohzu** [comment]
@mahya8585 差し替えておきました〜 👍  よろしくお願いします！

**Comment by mahya8585** [comment]
ありがとうございます><（Githubからプッシュきてびびった。。
送付だん
