### ISSUE TITLE
Microsoft請求書再作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#107]
私の実印を押してカラーコピー＆ｐｄｆ郵送

**Comment by mahya8585** [comment]
@kanakogohzu 

> 請求書については、イベント開催日の日付を発行日として作成いただくことは可能でしょうか。

とのことなので、日付変更おねがいできますか。
そのあとスプレッドシートのままGoogleDriveにいれておいていただけますでしょうか。
（私の方で印鑑入れてpdf送っておきます

**Comment by kanakogohzu** [comment]
@mahya8585 
こちらでお願いします 💁 
https://docs.google.com/spreadsheets/d/1Mx4_5McaSQv84so3XePD0NzP3aKN3oH7PDTB7OudcOs/edit

なお各見積書、請求書のスプレッドシートはいかに全部格納してあります！緊急時にはこちらも使って下さい 🙏 
スポンサー＆コミュニティ> 請求書・見積書>請求書・見積書ドラフト

**Comment by mahya8585** [comment]
ありがとうございます！
ドラフトディレクトリ見逃してました><!次回緊急時はこちらを利用します・・・！

ハンコまで押したので後郵送するだけ！
一旦チケットはクローズしてしまいます
