### ISSUE TITLE
確定スポンサーをSNS周知

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#109]
#108 と日程が被らないようよしなに調整
- [x] Microsoft
- [x] サーバーワークス
- [x] PayPal
- [x] GitHub Japan
- [x] focusrite
- [x] 株式会社ビジネスブレイン太田昭和
- [x] 株式会社ハッピーコム
- [x] spicelife
- [x] 株式会社アットウェア
- [x] 株式会社パソナテック
## 確定次第以下も
- [x] アトラシアン
- [x] 個人スポンサー（長沢さん）
- [x] GxP

**Comment by mahya8585** [comment]
2個〜3個ずつ流す

**Comment by okohs** [comment]
Buffer (https://buffer.com/) 使って流している。
現状確定している以下はBufferで全て予約済み (時間：AM8:00, 正午, PM:7:00)
- Microsoft
- サーバーワークス
- PayPal
- GitHub Japan
- focusrite
- 株式会社ビジネスブレイン太田昭和
- 株式会社ハッピーコム
- spicelife
- 株式会社アットウェア
- 株式会社パソナテック

**Comment by omame1986** [comment]
以下新たに投稿＆予約済み(時間：AM8:00, 正午, PM:7:00)
- アトラシアン
- GxP
- 長沢さん
- oisix

以下はロゴや写真が出次第順次登録します
- セールスフォース
- クラスメソッド
- 鈴木会長

**Comment by omame1986** [comment]
Microsoftさん流していない？
流しますね

**Comment by omame1986** [comment]
bufferでやっていなかっただけでした。本twitterの方にありました。失礼。

**Comment by omame1986** [comment]
- [x] クラスメソッド
- [x] セールスフォース
- [x] 鈴木会長

**Comment by omame1986** [comment]
- [x] keynote (Github)
- [x] スポンサーセッション Microsoft
- [x] スポンサーセッションAtlassian　成功するチームの隠し味
- [x] スポンサーセッション グローバルセキュリティエキスパート株式会社 
  女性エンジニアの新しいキャリアパス～ホワイトハッカーという選択肢～

**Comment by mahya8585** [comment]
これもだいたい完了したのでクローズしまーす
