### ISSUE TITLE
共催コミュニティを集める

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#11]

**Comment by mahya8585** [comment]
4月くらいから

**Comment by okohs** [comment]
やっぱり6月くらいから

**Comment by mahya8585** [comment]
5月中にフォームとか作成する

**Comment by mahya8585** [comment]
7月4日までに募集開始
- しょこ
  - gooleフォーム＆slack連携
- マーや
  - 募集文章作成

**Comment by okohs** [comment]
Googleフォーム作成してSlack連携もしたよ

## Google Form

http://goo.gl/forms/ZMb8n1GOF1ZIi2J23

## Slack連携先チャンネル

collabo_community

こんな感じでFormの内容が通知される
<img width="620" alt="2016-06-26 12 11 10" src="https://cloud.githubusercontent.com/assets/10089070/16360317/287db760-3b97-11e6-8384-53bc3b2860cf.png">

**Comment by okohs** [comment]
とりあえず10コミュニティ集まった。いぇい。
dots.女子部が増えそう・・・
