### ISSUE TITLE
spice life スポンサーリンク追加

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#110]
spicelifeのリンクをカンファレンスページへ追加お願いします
- Quarz
- ロゴはGoogleDriveのスポンサーロゴディレクトリに
- リンクURL 
  - spicelife : http://spicelife.jp/
  - Tmix : https://tmix.jp/

物品のため、どこの商品なのかサービスURL(Tmix)もどこかに張りたいと思います。spicelifeと並べて張るのがいいのかな？
デザイン感はお任せいたします・・・！

**Comment by okohs** [comment]
@mahya8585 QuarzだとスペルミスだからQuartzでHP更新するね。
ロゴは並べてみた

**Comment by mahya8585** [comment]
スペルミスありがとうございますw
よろしくお願いします

**Comment by mahya8585** [comment]
@okoysm 見ました配置良いと思います。
リンクって貼れますか？すぐすぐじゃなくても良いのでロゴに↑のリンク貼っていただけると嬉しいです。
よろしくお願いします

**Comment by Gyori** [comment]
dots側に追加しました。ハッピーコムさんだけ何スポンサーかわからなかったのでどなたかヘルプ頼んます

**Comment by okohs** [comment]
@Gyori ハッピーコムさんはSapphireスポンサーです！
同じ人から来ているメディアスポンサー（Happyデジタル）はAmberです！
カンファレンスページのソースを見ると、ロゴは登録されていないけどスポンサーな方々が見れるようになっている

**Comment by okohs** [comment]
@mahya8585 spicelifeさんのロゴ、一枚の画像にしているのだけど、分けて、それぞれのリンクを貼ったほうが良いかな・・・？

**Comment by mahya8585** [comment]
それぞれのリンクのがよさそう・・・

**Comment by Gyori** [comment]
難しいぜｗ
dotsページ、直しました。都度修正しますんで、問題あったら教えてくださいー。

ハッピーコムさんは会社のHP自体がHappyデジタルにしてるみたい（co.jpからリダイレクトされる）なので、ハッピーコムのリンクは「会社概要」のページを貼っておきました。

**Comment by okohs** [comment]
HP更新だん
