### ISSUE TITLE
Tシャツデザイン納品テンプレートの作成を行う

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#111]
@omame1986 @okoysm 
Tmixさんより印刷テンプレートが到着いたしました。

他の作業もりもりの中大変申し訳ないんですがロゴの配置をお願いできますか
よろしくお願いします。

Googleドライブ>CoreCast>素材>Tシャツ

**Comment by mahya8585** [comment]
@okoysm @omame1986 

【データ締切日】2016年10月17日（月）

先日お送りしたテンプレートファイルに記載の注意事項をお読みの上、
デザインエリアレイヤーに印刷する柄を配置してデータの作成をお願いいたします。

お渡ししたテンプレートでは白Tシャツになっておりますが、
デザインしやすいようTシャツに着色頂いて大丈夫です。

印刷に使用するインク色を3色お選びください。
テンプレートに記載の見本50色からお選びいただくのがスムーズですが、
その他 DIC や PANTONE での色指定も可能です。
**※メールに番号出てるので、確認してください**

金曜に一時作成して先方に送付＆確認してもらいたい(希望)

**Comment by okohs** [comment]
![tshirt_omote](https://cloud.githubusercontent.com/assets/10089070/19358778/2a4f7224-91b2-11e6-8302-d248da1ea4b6.png)

**Comment by okohs** [comment]
Driveのイラレデータを更新した。
インクの色調整済み https://drive.google.com/drive/folders/0B2jun1de3VScbUstR21Vb0RYUTA

**Comment by mahya8585** [comment]
受領。メールで送っておきます
