### ISSUE TITLE
MS登壇情報収集

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#112]
登壇情報集まり次第しょこさんにHP登録してもらう。
まだ1人分しか送られてきてないので、全員そろってからにする

ディレクトリ
- スポンサー＆コミュニティ>登壇データ
- MVPスピーカー
  - 松本典子
    - 株式会社オルターブース　デザインアーキテクト
    - JAZUG女子部

**Comment by mahya8585** [comment]
■登壇者
日本マイクロソフト株式会社　テクニカルエバンジェリスト
戸倉 彩
千代田 まどか

■セッション概要
マイクロソフトは、「お客様の可能性を最大限に引き出すための支援をすること」というミッションに基づき、絶えず製品やサービスをアップデートし、より良いものにしてきました。今回は、多種多様な経験と価値観を持つ人材を受け入れるマイクロソフトのダイバーシティや、WEBデザイナー視点から見たAzureクラウドの魅力、最新のマイクロソフトテクノロジーのトレンド情報をデモを交えてお届けします。

■90分セッションの大枠な流れ
・5分 メンバー紹介 (MS戸倉彩)
・25分 ダイバーシティについて (MS千代田まどか氏)
・30分 WEB制作視点でAzureクラウドを使ってみた話 (松本典子氏)
・30分 最新マイクロソフトテクノロジーのトレンド情報(MS戸倉彩)

**Comment by okohs** [comment]
HP反映done
