### ISSUE TITLE
BBS掲載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#114]
ドライブのロゴ入れにビジネスブレイン太田昭和のロゴいれました。
対応お願いします。

dots-> @Gyori 
カンファページ -> @okoysm 

合わせて登壇者情報もお願いします。

```
「女性エンジニアの新しいキャリアパス～ホワイトハッカーという選択肢～」
グローバルセキュリティエキスパート株式会社  小倉佳世
```

※ビジネスブレイン太田昭和の子会社のセキュリティ教育のインストラクターの方

**Comment by okohs** [comment]
HPだん
