### ISSUE TITLE
WWC × Djangoのセッション概要を追記

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#119]

**Comment by mahya8585** [comment]
タイトル
プログラミング未経験者歓迎！Pythonでじゃんけんゲームを作ろう。

概要
プログラミング未経験、初心者向け。
Pythonでじゃんけんゲームを作ってブラウザで動かしてみよう。
Python基礎のレクチャーを聞いて、実際にコードを書いてみましょう。
ノートパソコンお持ちでない方は、手書きで書いて持ち帰る事も出来るよ！

カンファレンスページへの追記お願いします。

**Comment by okohs** [comment]
HP反映done
