### ISSUE TITLE
ロゴを作る

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#12]

**Comment by mahya8585** [comment]
![logo-1](https://cloud.githubusercontent.com/assets/10239748/12005509/ff15d55a-abeb-11e5-9c82-f7d7ac05d975.png)

仮ロゴあるので急いでない。

3月末まで

**Comment by mamix1116** [comment]
ロゴは2月末までにつくる。
コミュニティースポンサー第１弾（３月末）がついたら、ステッカー/ネイルをつくる。

**Comment by mahya8585** [comment]
ロゴイメージ
- 綺麗系
  - 女性のシルエットとか
- 上の3色のみで作成
- あまり細くないデザイン
- Geek感が欲しい
  - パソコンとか

**Comment by mahya8585** [comment]
わたしのお友達にも案作成依頼だしました。

**Comment by mahya8585** [comment]
@mamix1116 @NahoInuyama @satomyumi @sd-ts1017 
googleドライブの以下ディレクトリに案を置きました。みなさん色々意見ください。お願いすれば色々修正可能だし、この後aiファイルももらえるそうなので好きにカスタマイズしてもOKだそうです。

CoreCast >  資料とかに使える素材 > ロゴ案

**Comment by mahya8585** [comment]
個人的には2-1が気に入っている

GWJモチーフの蝶々をもっとポップな感じにできるのであれば、
- 緑 + ピンクで
- ポップなGWJ蝶々
- システム言語で書かれた軌道(logo3のやつをもっと大きく書いたもの) 

にしたらかわいいのではないか、と思っています

**Comment by okohs** [comment]
個人的にはlogo5が好みー！蝶モチーフ良い！
右下のお花の桜感よい(桜モチーフ大好き
logo5-2くらいGWJが太いと遠目でも見えてよさげ。

**Comment by mahya8585** [comment]
まぜまぜ案で決定ー
