### ISSUE TITLE
GTUGGirls × クラウド女子会 セッション内容掲載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#124]
- セッションタイトル

「◯◯の知らない世界」
- セッション概要

第1部 : GTUG&クラウド女子会のご紹介
第2部 : GTUG Girls恒例のなごみタイム＼(^o^)／会場参加者を巻き込んで、お茶をしながらアイスブレイクします。
第3部 : パネルディスカッション。GTUGGirlsの知らないJAWS-UG クラウドの世界＆JAWS-UG クラウド女子会の知らないGTUGGirlsの世界。
            各コミュニティの深部に迫るトークと、これまで行ってきたイベントから選りすぐりの内容をご紹介（軽め）

**Comment by okohs** [comment]
HP反映done
