### ISSUE TITLE
スピーカ募集する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#13]
スピーカーは女性のみ

**Comment by mahya8585** [comment]
8月頭にCfP 募集開始
9月頭に運営クローズ選定
9月半ばに公開投票選定
10月頭にCfP当選者発表

**Comment by okohs** [comment]
公開投票する時にクローズ選定したCfPは発表する

**Comment by okohs** [comment]
募集方法は要検討。

**Comment by mahya8585** [comment]
コミュニティコラボ型セッションに決定。
これに伴いCfPなしに決定
