### ISSUE TITLE
GxP 掲載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#130]
dot-> @Gyori 
HP -> @okoysm 

グロースエクスパートナーズ

**Comment by okohs** [comment]
@mahya8585 これ個人スポンサーなのかな・・・
仮にも企業名を出しているので、SapphireなりEmeraldなりで出した方がいい気がする

**Comment by okohs** [comment]
HP反映done

**Comment by mahya8585** [comment]
GxPはサファイアで企業スポンサードいただいてます。
(別途ユースケさんの個人スポンサーの件話が進んでます。こちらはまた別チケットにて。

**Comment by omame1986** [comment]
dots反映done
