### ISSUE TITLE
オリンピックセンターに問い合わせ

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#134]
以下をオリンピックセンターに電話問い合わせ願えますでしょうか。
@Gyori @omame1986 @kanakogohzu どなたか早めに動けるかた・・・！よろしくお願いしあmす

> 当日利用できるプロジェクターの入力端子の規格と推奨解像度の情報を各部屋分

**Comment by kanakogohzu** [comment]
明日記者発表会があり、17時くらいまで私が拘束されてしまっているのですが、それ以降でしたら電話可能です。

**Comment by mahya8585** [comment]
お願いしまーす

**Comment by kanakogohzu** [comment]
了解です(｀･ω･´)ゞ

**Comment by kanakogohzu** [comment]
わたわたしてたら17:45までが電話受付時間だったorz
明日朝連絡しますorzorzorzorzorzorz

**Comment by kanakogohzu** [comment]
確認取れました！
VGA端子で1024×768です(｀･ω･´)ゞ

**Comment by kanakogohzu** [comment]
> VGA端子で1024×768です(｀･ω･´)ゞ

これどこかに周知したほうが良いです…? 🤔

**Comment by mahya8585** [comment]
スポンサーに連絡いれておきます
