### ISSUE TITLE
アトラシアンセッション概要掲載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#135]
登壇者：犬山奈穂
セッション名：成功するチームの隠し味
セッション概要：同じ開発チームでも、バグが頻発するチームとしないチームがあるのはどうしてでしょう？また、障害をいつまでも復旧できないチームと、すぐに解決してしまうチームがあるのはどうしてでしょう？アトラシアンでは、異なる人種や性別だけでなく、性格やアイデンティといった見えない多様性の中で、パフォーマンス性の高いチーム（=成功するチーム）を築き上げる努力をしています。その「隠し味」をみなさんと共有したいと思います。

掲載何卒よろしくお願いいたします。
写真もドライブにあげております。

**Comment by okohs** [comment]
修正done
