### ISSUE TITLE
Bufferに予約投稿を設定する

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#137]
Bufferを使ってツイートの予約投稿をしてください
## Bufferとは

以下にGeekWomenJapanのTwitterアカウント使ってログインしてください。  
触れば分かる（雑
https://buffer.com/
### 追加スポンサー　（こちらを先に）

Oisix, Atlassian, GxP, 長沢さんが入ってないと思うのでお願いしたい
### スピーカー
- keynoteスピーカー
- スポンサーセッションスピーカー（枠ごとでいいと思う）
### 参加登録への誘導ツイート
- 同じものでいいので一日一回どこかに入れてください（この前まではずっと12amだった）
## その他Bufferの設定
- スケジュールはもともとの設定どおり（8am, 12am, 7pmの一日３回)
- 多少ずらすのは有りかもしれないのでそこら辺は任せますー！

**Comment by omame1986** [comment]
チャレンジしてみます。

**Comment by omame1986** [comment]
とりあえず１件Queueに入りました。
明日から
8am、7pmにスポンサー情報
12amに参加者登録呼びかけ
という風に入れていきます。
（要はこれまで通りですね）

で、スポンサー情報出し終わったらkeynoteスピーカーとスポンサセッションのフェーズに入るような
スケジュールにしますね。

**Comment by omame1986** [comment]
確定したスポンサーと
スポンサーセッション(タイトルでてるもの)
とkeynote
はすべて流しました
次はコラボセッションタイトルでも流しますか？

**Comment by mahya8585** [comment]
@omame1986 以下登録お願いできますでしょうか。
- [x] クラスメソッドで掲載してもらったよ
  - http://dev.classmethod.jp/news/geek-women-japan-2016/
- [x] 当日名札できたよ(写真付き)
- [x] フォトプロップできたよ(写真付き) @okoysm から写真もらってね
- [x] アストロ君当日配布するよ(写真付き)。セールスフォースのキャラクターだよ。 @mahya8585から写真送ります

**Comment by mahya8585** [comment]
![slack for ios upload 1](https://cloud.githubusercontent.com/assets/10239748/19763011/4c16876a-9c77-11e6-87c0-1dddfe9e33f1.jpg)

アストロ君です。託児室にいっぱい並べてお子様に配布したいと思うよー

**Comment by omame1986** [comment]
- [x] クッキー配布するよ（写真つき）
- [x] 託児申込できるよ！先着順だよ！
- [x] GxPのスポンサーセッション

**Comment by mahya8585** [comment]
これだいたい終わったので一回クローズしますよー
この先は都度設定ということで
