### ISSUE TITLE
カンファレンスページ・dotsページにwifi情報を掲載する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#138]
(MS戸倉さんからの指摘)

参加者用のwifiは用意していません、の情報を追記
- dots -> @Gyori 
- HP -> @okoysm

**Comment by omame1986** [comment]
dotsページに以下を追加

## 当日の会場について
- 参加者用の無線wifiはありません。必要な方は各自でご用意ください
- 電源コンセントはあります。

**Comment by okohs** [comment]
HP反映done
