### ISSUE TITLE
個人スポンサー鈴木さん掲載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#139]
鈴木雄介（グロースエクスパートナーズ株式会社 執行役員/日本Javaユーザーグループ 会長）
で掲載お願いします。
写真をドライブにあげました

dots -> @Gyori 
HP -> @okoysm

**Comment by Gyori** [comment]
dots対応しました

**Comment by okohs** [comment]
HP反映done
