### ISSUE TITLE
海外ゲストどうするか協議する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#14]
きょんさんが翻訳やってくれるよ。

**Comment by okohs** [comment]
Girl Geek Dinners
http://girlgeekdinners.com/locations/partners-by-location/

**Comment by mamix1116** [comment]
会場とスポンサー次第で。。
・Github、WWCode、GeekGirls、アトラシアン

・みんなが使うツール
・女性のコミュニティーの運営や、女性キャリア

**Comment by mamix1116** [comment]
キーノート　１つかな。

**Comment by okohs** [comment]
HangOutセッションいいね！

**Comment by okohs** [comment]
なほさんアサインする！

**Comment by okohs** [comment]
まずGitHubで

**Comment by okohs** [comment]
GitHubにアタックした。
