### ISSUE TITLE
クラスメソッド投稿文章の作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#141]
@omame1986 @okoysm @kanakogohzu 
クラスメソッドのサイトに載せる文章の作成をお願いできますでしょうか。

```
こちらはリード文とイベント概要をいただいてから掲載いたします。
　お手数ですが、リード文、イベント概要、その他掲載したい画像などをいただけますでしょうか。
```

基本的にはカンファレンスページに書いてあることを抜粋して繋ぎ合わせれば良いかと思います。
忙しいところ申し訳ございませんがよろしくお願いします！

**Comment by okoysm** [comment]
参考になりそう
1つ目は、データなどの数字をできるだけ入れることです。
文章全体の信頼性が高まり、読んでもらいやすい文章になります。たとえば、「2012年に文部科学省が発表したデータによると～」といった具合ですね。

2つ目は、リード文中に注目されているキーワードを取り入れることです。
注目されているキーワードは読者が検索しやすいので、読者を引きつけるためには冒頭に置いておきたいですね。

3つ目は応用ですが、書き出しに体言止めを使うとインパクトがあるリード文になります。
「音楽好きなら一度は弾いてみたい憧れの楽器、アコースティックギター。」という具合です。

**Comment by okohs** [comment]
これ参考になりそう
http://dev.classmethod.jp/smartphone/android/android-all-stars-2/

**Comment by omame1986** [comment]
たたき作成します。レビューしてもらえたらうれしい

**Comment by omame1986** [comment]
小出しにするね

リード文
`
2016年11月3日(木曜、祝日)に、女性エンジニアが中心となって一同に集まり、ギークなセッションを繰り広げるカンファレンスが行われます。
主催はGeekWomenJapan。技術に縛られず、女性エンジニアの輪を広げ新しい知識や発見をしようという団体です。男性もご参加いただけます。
共催女性エンジニアコミュニティによるコラボセッション、「GitHub社」によるKeynoteセッション、各社スポンサーセッションを予定！
技術に興味をお持ちの方、男女問わずぜひご参加ください。
`

**Comment by omame1986** [comment]
ちなみにサンコー
[「いまからはじめるIoTのAtoZ〜センサーデータ活用編〜」を開催します](http://classmethod.jp/news/%E3%80%8C%E3%81%84%E3%81%BE%E3%81%8B%E3%82%89%E3%81%AF%E3%81%98%E3%82%81%E3%82%8Biot%E3%81%AEatoz%E3%80%9C%E3%82%BB%E3%83%B3%E3%82%B5%E3%83%BC%E3%83%87%E3%83%BC%E3%82%BF%E6%B4%BB%E7%94%A8%E7%B7%A8/)

**Comment by omame1986** [comment]
タイトル
女性エンジニア・コミュニティが中心となって「GeekWomenJapan2016」を開催します！

リード文
↑の

概要

日時：2016年11月3日（木、祝） 10:00〜19:00 (開場9:00)
場所：国立オリンピック記念青少年総合センター (〒151-0052　東京都渋谷区代々木神園町3-1)
参加費：無料

本セミナーの詳細、お申込みはイベントサイトをご覧ください。
http://geekwomenjapan.github.io/conference2016/index.html
