### ISSUE TITLE
写真NGの人のためのリボンを用意する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#146]
```
写真は困るという場合は当日受付にお申し出ください。写真NGストラップをお渡しします。ストラップを付けている方の写真が、レポート記事等に掲載されないよう配慮させて頂きます。ただし、会場全体の風景写真や後ろ姿など個人が特定されにくい写真に写り込んでしまうかもしれませんので何卒ご容赦ください。一切の写真の公開を望まないお客様は、あらかじめスタッフまでお知らせください。
```

というコードオブコンダクトがあるので、NGの人用のリボンを用意したいと思います。
（ネームtagと一緒に首から下げてもらう想定です。）

内職できるかたいらっしゃいませんか・・・
50本ほど用意したいと思います

**Comment by kanakogohzu** [comment]
フォトドロップ作成作業と一緒に片付けられそうです。100均で調達しますね。 👍 
悩むのは色ですね。色は目立つ方がいいですよね、黄色とか赤とか?

**Comment by mahya8585** [comment]
赤とか黄色いいですね。おねがいします。
目立つやつ

**Comment by okohs** [comment]
これ当日受け付けにボックスとか置いておいたほうがいいかもね
「写真NGの方はこちらのリボンをネームタグにつけてください」てきな

**Comment by mahya8585** [comment]
リボンを首から下げられる長さにしよう。首にかかってると目立つし、後ろからでもわかるので。

箱でもいいし受付に張り紙して置いておくでもいいかも

**Comment by kanakogohzu** [comment]
赤いリボン10ｍ買いました 😄 
切って受付で渡すの良さそうですね

**Comment by mahya8585** [comment]
切る作業は事前にやっておくようにしましょう。できればわっかにしておくところまでやっておきたいです。
@kanakogohzu  当日受け付け始まる10分前から来れますか？受付開始前に2-3本作成をお願いしたいです。
（そっから先は資材搬入班のボランティアスタッフ2名ほどに作業おねがいしてもらって構いません。）

このコメント確認いただいたらチケットクローズしてOKです

**Comment by kanakogohzu** [comment]
もちろんです！
