### ISSUE TITLE
参加者にアンカンファがある旨メール通知する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#148]
- 午後アンカンファありますよ
- アンカンファ受付は朝からやってるよ
- 発表したい人は資料準備しておいてね！

**Comment by okohs** [comment]
アンカンファって資料必須？任意でもいいかなーと思ってた

**Comment by mahya8585** [comment]
もちろん任意でOKですよ！
事前に準備したい、って人がいたらあれかな、と思っただけでした。
とにかくアンカンファあるよってことをメールで送れればいいかなと。

**Comment by mahya8585** [comment]
あとあれだ、当日wifiない旨連絡

**Comment by okohs** [comment]
リアルタイムにやりとりしててウケたｗ
そうね、そのへんちょっと書いておきましょう。

**Comment by mahya8585** [comment]
12時に予約配信済み
あ、細かいことは書いてないw
