### ISSUE TITLE
GxPセッション概要追加

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#151]
- セッションタイトル
  29歳の私が色々な人に聞いてみた『ちょうどいい働き方』 〜ところで、お仕事は好きですか？〜
- セッション概要
  世の中には「女性のキャリア」という言葉があふれていますが、
  意外に身近な人とはそういう話をしたことがないことに気付きました。
  自社に色々なキャリアの女性エンジニアがいるので『ちょうどいい働き方』を
  テーマに話し合いをしてみた結果を会場の皆さんと共有したいと思います。

**Comment by mahya8585** [comment]
起票ありがとうございます。反映よろしこねがいします

**Comment by okohs** [comment]
HP反映done
