### ISSUE TITLE
スタッフTシャツ着用写真を送付する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#160]
- Tシャツを着用されているスタッフ様の集合写真
- Tシャツの全体＆柄のアップ写真（着用時・平置きどちらでも）

のいずれか、または両方を頂戴できましたらありがたいです。

頂戴したお写真は弊社アカウントでのスポンサー事例報告など、
ウェブで使わせていただく場合がありますので、
もしお顔が写っていると問題のあるものがありましたら、首より下のみ使う、
またはお顔がわからないように加工して使わせていただきますので併せてお知らせいただけましたら幸いです。

------------------------------------------------------------

ということでスタッフみんなでTシャツ着て写真とるぞー！

**Comment by okohs** [comment]
朝撮影する

**Comment by mahya8585** [comment]
mailから送付だんです。
