### ISSUE TITLE
サファイアスポンサー欄にhappyデジタルを追加する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#161]
掲載されていない様子（先方からプチクレームあり（クレームってほどじゃないけど））。
HP＆当日配布タイムスケジュールへの追加をお願いします

**Comment by okohs** [comment]
ロゴないから出してなかった。Happyデジタルと同じでいい？

**Comment by mahya8585** [comment]
あ、なるほど
Happyデジタルでよいようなので、アンバーと同じものの設定をお願いします。

**Comment by okohs** [comment]
りょうかい！帰ったら対応します

**Comment by okohs** [comment]
HP反映done
