### ISSUE TITLE
張り紙、タイムボードの印刷

### ISSUE THREAD

**Issue by omame1986** [GeekWomenJapan/CoreCastWorks#164]
まーやさん印刷おなしゃす！
[GWJP印刷.pptx](https://github.com/GeekWomenJapan/CoreCastWorks/files/561734/GWJP.pptx)

**Comment by omame1986** [comment]
誘導用印刷物の追加

**Comment by omame1986** [comment]
[GWJP印刷.pptx](https://github.com/GeekWomenJapan/CoreCastWorks/files/566266/GWJP.pptx)
こっちでおねがいします！

**Comment by okohs** [comment]
お疲れ様！！！
