### ISSUE TITLE
スポンサー前日メール

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#167]
- [x] 写真について
- [x] イベントレポート掲載について
- [x] 登壇前チェックについて
- [x] ノベルティについて
- [x] 懇親会について
- [ ] その他不明点あればどうぞ

**Comment by okohs** [comment]
- [x] ブース設営可能時間

**Comment by mahya8585** [comment]
合わせてコミュニティにも送付済み
