### ISSUE TITLE
togetterを作成する

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#169]
全体+部屋別かな？

**Comment by mahya8585** [comment]
全体
http://togetter.com/li/1044617

opening〜keynote
http://togetter.com/li/1044619

roomB
http://togetter.com/li/1044623

roomC
http://togetter.com/li/1044626

までやって力尽きた・・・
どなたかroomD/E 頼んだ・・・

**Comment by mahya8585** [comment]
@okoysm @Gyori @kanakogohzu @omame1986 @mamix1116 
やれそうな方いたら assign yourself お願いします

**Comment by mahya8585** [comment]
時間が経ちすぎてしまい、もうまとめられない・・・（まとめ対象にでてこない

**Comment by okohs** [comment]
done.にしよう。
