### ISSUE TITLE
振り返りする日を決める

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#170]

**Comment by mahya8585** [comment]
19日の打ち上げで。
打ち上げに参加できないメンバーは事前にKPTつけてください

**Comment by mahya8585** [comment]
@okoysm @Gyori @kanakogohzu @mamix1116 @omame1986 @mahya8585
以下KPTファイルです。12月19日までに入力をお願いします。来年の糧にしたいと思います。

https://docs.google.com/spreadsheets/d/1prclhmxwDhfhnpDpr4cAfGOcm_vDwz1xY2JY5zzmGAM/edit#gid=0
