### ISSUE TITLE
経費精算する

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#171]

**Comment by mahya8585** [comment]
コアキャスト＞お金＞収支
総収支欄に記入ください

15日までにお願いします

**Comment by mahya8585** [comment]
領収書はオープンストリーム石田まで送っていただくか、次回会ったときにください

**Comment by okohs** [comment]
一旦全員アサインしたから、入力し終わった時点で自分をAssigneeから外してね

**Comment by mahya8585** [comment]
まだwifiの正式請求書が届いていないので、これを待って各自入金処理を行います。

↑の前に確認するべき記入項目について各自へslackで質問を投げますので対応よろしくおねがいしますー

**Comment by okohs** [comment]
12/19の打ち上げにて @kanakogohzu @okoysm は済

**Comment by mahya8585** [comment]
ぎょりちゃん振込完了
石田立替分清算済み

みほさん分引き出し・封筒に入れて準備完了。あと渡すだけ。

現時点の収支表更新済み。

[残タスク] @omame1986 分

**Comment by mahya8585** [comment]
新年会2017でみほさんにもお渡し済み。
done.
