### ISSUE TITLE
団体登録

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#178]
Geek Women Japanの団体登録をするのは
- オリセン
- 青山ウィメンズプラザ

**Comment by mahya8585** [comment]
## オリンピックセンター

http://nyc.niye.go.jp/d1-2-html/

- 定款、規約、会則、要覧、概要等団体の資料
- 団体構成員名簿
- 開催する研修の企画書や開催要項など

銀行口座作るときに作った資料をそのまま印刷すれば行けそう


## ウィメンズプラザ

http://www1.tokyo-womens-plaza.metro.tokyo.jp/facilities/tabid/171/Default.aspx

- http://www1.tokyo-womens-plaza.metro.tokyo.jp/Portals/0/images/facilities/dantai_groupe_tourokumoushikomisyo.pdf
- 設立趣旨がわかる規約、定款
- 活動内容及び活動実績が確認できる資料（機関誌、チラシ、パンフレット等） を添付のうえ、
当館２階施設予約窓口へご提出ください。

郵送でも受け付けています。
審査終了後（書類受付から約１ヶ月後）、登録となる団体・グループには、登録カードをお送りします。

こちらも銀行作った時と同じ資料で行けそう


近々行けそうな方ご連絡ください

**Comment by kanakogohzu** [comment]
@mahya8585 
準備としては、①申込書に要件記入、②活動実績としてWEBサイトを印刷して提出という感じですかね 👀 
郵便局近いし、行く必要があるとしても午前中自由に動けるのでやりますよ(｀･ω･´)ゞ

**Comment by mahya8585** [comment]
ではとりあえずウィメンズプラザお願いしてもいいですか！
ウィメンズプラザについては↑の認識でOKです。

オリンピックセンターについては実際に窓口に行かないとダメなのでござる。
もし行けそうならお願いしたいです！

**Comment by kanakogohzu** [comment]
オリンピックセンターもOKでござります(｀･ω･´)ゞ

**Comment by kanakogohzu** [comment]
@mahya8585 銀行口座作成するときに使った資料の場所教えてください 🙇

**Comment by mahya8585** [comment]
https://drive.google.com/drive/u/0/folders/0B2jun1de3VScU0Q2Q0g2Z3R4OUU
ここです！

団体規約と会員名簿、分かる範囲で書き直しておきました。クロスチェックお願いします。
（怪しければ修正してしまっておけーです！）

これプラスでカンファレンスページと新年会のdotsの申し込みページとか持っていけば良いかと思います。

**Comment by kanakogohzu** [comment]
ありがとうございます 🙇 
確認してこちらで作業すすめてみます(｀･ω･´)ゞ

**Comment by kanakogohzu** [comment]
( ﾟдﾟ)ﾊｯ!進捗書いていなかった。ウィメンズは書類送って審査中でございます。オリンピックセンターは水曜日にいてくる(｀･ω･´)ゞ

**Comment by kanakogohzu** [comment]
オリンピックセンター行ってきた＆申請してきたので学んだことを記載しておきます 📝 

## 必要書類
- 名簿5名分
 - 氏名、年齢、住んでる都道府県
- 活動がわかる書類
 - 団体運営規約、新年会レポートのページのコピー、カンファレンスレポートページのコピーでOKでした

## 事前に決めるべきこと
- 初回の施設利用の予約の日程
 - 二回目からは電話でいいらしいので問題はなさそうだけど完全に罠だった

## その他学び
- 住所情報はマンション名まで書かないといけない
- 一般団体が予約できるのは10ヶ月先まで
- 「参加者は青少年ですか」的な問があったが、意味不明だったのでスルーした
- ルールですので～といういちゃもんはだいたい嘘なので「規約のどこに書いてあります？」と聞くとだいたいはねのけられる
- 部屋を借りる際には部屋番号ではなく収容人数で指定しないと職員の人が受理してくれない
 - 例：「404」ではなくて「20名の部屋」
 - 人数に基づき貸出しているからそういうオペレーションらしい 😓

**Comment by kanakogohzu** [comment]
申請完了したら私宛にはがきがおくられてくるので、それ待ちです 🌀

**Comment by mahya8585** [comment]
すったもんだの末無事オリセン申請完了

**Comment by kanakogohzu** [comment]
いぇいYOYO
ウィメンズプラザはまだ連絡来ず…

**Comment by okohs** [comment]
ウィメンズプラザ団体登録完了。
id,pwはaccountチャンネルに。
