### ISSUE TITLE
会場にwifi 立てる準備する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#18]

**Comment by mahya8585** [comment]
アクセスポイントでも可

**Comment by mahya8585** [comment]
会場決まり次第当日まで活動

**Comment by mahya8585** [comment]
JJUGでざっとみつもったところ、企業に頼むと60～100万程度かかる。
本当にたてるか要検討。

会場にどの程度のネット環境が用意されているのか要検討の必要あり

ちなみにJJUGで30台接続できるAPを2台購入しているので、お願いすれば借りれると思う。30台接続というのが微妙だけれども。。。

**Comment by okohs** [comment]
30台接続となると、登壇者分＋スタッフ分とかできるかもね

**Comment by mahya8585** [comment]
ぽけっとwifiを部屋数分

**Comment by okohs** [comment]
電源タップを会場費のあまりとかで頼みたい

**Comment by mahya8585** [comment]
9月中見積もりとる。絶対

**Comment by Gyori** [comment]
必要な部屋にだけ置く前提でこれで良いかなーと思っている
http://www.netage.ne.jp/

**Comment by Gyori** [comment]
10/11（火）の週で有償で借りるかどうするか決める

**Comment by mahya8585** [comment]
Microsoftさん経由だと6機6万弱とのことだったので、 @Gyori さんが見つけてくれた方でレンタル進めましょう！
処理進行よろしくお願いいたします！

**Comment by Gyori** [comment]
個人申込、立替精算で良いです？
9台借りようかと思ってまして、6,000円ぐらいの見込ですー。
https://drive.google.com/file/d/0B0Vs20dDhCZmSGRuSE0tMHZCX2s/view?usp=sharing
@mahya8585

**Comment by mahya8585** [comment]
オケでーす

**Comment by mahya8585** [comment]
福岡から帰還次第発注開始
- 個人申込
- 立替清算お願いします><!

領収書はGeek Women Japanでもらってください（無理なら個人名で

**Comment by Gyori** [comment]
注文done

> ■受け付け番号  ：2016101617462601
> 
> ■レンタル機器とご利用料金：
> 
>   Y!mobile レンタル(A) 305ZT × 3 台
>     \* 1台分の料金は、400円(税込432円)/日、6,000円(税込6,480円)/月
>     \* 3台分の料金は、1,200円(税込1,296円)/日、18,000円(税込19,440円)/月
>   Y!mobile レンタル(S1) GL09P × 3 台
>     \* 1台分の料金は、400円(税込432円)/日、6,000円(税込6,480円)/月
>     \* 3台分の料金は、1,200円(税込1,296円)/日、18,000円(税込19,440円)/月
>   ドコモ レンタル(A) MF98N_2 × 1 台
>     \* 1台分の料金は、680円(税込734円)/日、9,800円(税込10,584円)/月
>   Y!mobile レンタル(A) GL06P × 2 台
>     \* 1台分の料金は、400円(税込432円)/日、6,000円(税込6,480円)/月
>     \* 2台分の料金は、800円(税込864円)/日、12,000円(税込12,960円)/月
>   モバイル レンタル 安心補償(A) × 9 台分
>     \* 1台分の料金は、40円(税込43円)/日、400円(税込432円)/月
>     \* 9台分の料金は、360円(税込387円)/日、3,600円(税込3,888円)/月
> 
>   貸出時の送料  ：宅配便、全国一律 500円(税込540円)/1個口（当社からご請求します）
>   返却時の送料  ：お客さまご自身で、宅配業者に直接お支払いください

**Comment by Gyori** [comment]
@gyori が対応します
Y!mobile レンタル(A) 305ZT × 3 台
- 1台分の料金は、400円(税込432円)/日、6,000円(税込6,480円)/月
- 3台分の料金は、1,200円(税込1,296円)/日、18,000円(税込19,440円)/月

@mahya8585 さん、おなしゃす
Y!mobile レンタル(S1) GL09P × 3 台
- 1台分の料金は、400円(税込432円)/日、6,000円(税込6,480円)/月
- 3台分の料金は、1,200円(税込1,296円)/日、18,000円(税込19,440円)/月

@okoysm さん、おなしゃす
ドコモ レンタル(A) MF98N_2 × 1 台
- 1台分の料金は、680円(税込734円)/日、9,800円(税込10,584円)/月
  Y!mobile レンタル(A) GL06P × 2 台
- 1台分の料金は、400円(税込432円)/日、6,000円(税込6,480円)/月
- 2台分の料金は、800円(税込864円)/日、12,000円(税込12,960円)/月

※すべて安心保証付き
※自宅に11/2に届くように手配しています
※11/3に持参する前提

よろしくお願いします。

**Comment by okohs** [comment]
@Gyori こちら私の分申し込みました！

**Comment by omame1986** [comment]
領収書ないんですね・・・
11/2着だと以下の見積もりになります
[WEB-EST-20161018215949-6D33.pdf](https://github.com/GeekWomenJapan/CoreCastWorks/files/536263/WEB-EST-20161018215949-6D33.pdf)

**Comment by omame1986** [comment]
- 安心保障付
- 3台
- 11/2に自宅へ着くように指定

で申し込みました

**Comment by okohs** [comment]
## Wi-Fiの分担
- 受付
- 遊撃
- 託児
- B, C, D, E部屋
- 予備 (2台)

**Comment by okohs** [comment]
Wi-Fi使うのはスピーカースタッフのみ

**Comment by okohs** [comment]
お疲れ様！！！
