### ISSUE TITLE
各登壇者へタイトル・概要・写真をもらう

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#180]
年明け中旬くらいまで。

写真はTwitterアイコンでもなんでもおけ

**Comment by mahya8585** [comment]
連絡を年内に。

返信は1月中旬をめどに

**Comment by mahya8585** [comment]
Geek Women メールボックスの下書きに作成済み。
ど深夜になってしまったので、送信は明日(19日)にしたいと思います。

一部登壇者はSNSでしか繋がってないもしくはSNSの方が返信もらいやすい、などありますので、メールで送りきれない分については石田から各登壇者に連絡いたします。

**Comment by mahya8585** [comment]
連絡チェックリスト
チェックボックスにチェック -> プロフィール受領
打ち消し線 -> 概要・タイトル受領

- RoomA
    - BigData
        - [ ] まかびー : PyLadies slack
        - [ ] 大森さん(MS) : MS経由
    - ソフトスキル
        - ~~みほ : GWJ slack~~
        - ~~なほさん : mail from GWJ~~
    - LT
        - ~~ごっち : GWJ slack~~
        - [ ] えりこ : maaya twitterDM
        - ~~まーや : 本人~~
        - [ ] 戸倉さん(MS) : MS経由
        - ~~ちゃんとく : GWJ twitterDM~~
        - [ ] 宇佐美友紀(うさみゆき)さん : mail

- RoomB
    - JS/エディタ
         - [x] 木村まゆ : mail & OPST slack
    - Android * Swift
        - ~~なみきさん(Android) : facebook group~~
        - ~~じょーいさん(Android) : facebook group~~
        - ~~行木さん(iOS) : facebook group~~
        - ~~須藤さん(iOS) : facebook group~~
    - CI/CD（DevOps)
        - ~~しょぼちむ確定 : maaya Twitter~~
    - AWS / Azure
        - [ ] 大平かづみさん : facebook group

**Comment by okohs** [comment]
> 一部登壇者はSNSでしか繋がってない、などありますので、メールで送りきれない分については石田から各登壇者に連絡いたします。

SNSでしかつながってないひと、Geek Women Japanのアカウントから連絡したらどうだろうか

**Comment by mahya8585** [comment]
Twitterならそれでおけーなんですが、facebook・slackで依頼していた人がいるもので、

- Twitter でやり取りしていた人：Geek Women アカウントから
- facebook/コミュニティSlackでやり取りできる人：各個人アカウントから

連絡するようにしたいと思いますー
今回対個人のため、個人からの返信をスピーディにもらえる方法で連絡取りたいと思いまする
あとMS登壇者については今度対面で会うのでそこでお願いしてきます。

**Comment by okohs** [comment]
なるほど、了解！ありがとう！

**Comment by mahya8585** [comment]
@okoysm 宇佐美さんの連絡先(mail/SNSなんでもいいです）ご存知でしたらslackでご共有いただけますか（明日とかで大丈夫です）

**Comment by okohs** [comment]
@mahya8585 Slackで送りました

**Comment by mahya8585** [comment]
done.全体的に返信待ち

**Comment by mahya8585** [comment]
https://github.com/GeekWomenJapan/CoreCastWorks/issues/180#issuecomment-273499226
@omame1986 にヘルプいただき(ありがとうございます！)、
現時点でもらっている情報すべてHP掲載PR済み。
（↑のチェックとずれているものがあったら指摘お願いします）。

## 残タスク

- プロフィール未受領
    - [ ] 宇佐美さん 

- タイトル未受領
    - [X] 大平さん
    - [ ] 宇佐美さん

- 概要未受領
    - [X] 木村さん
    - [X] まかびー
    - [ ] えりこさん
    - [X] 大平さん
    - [ ] 宇佐美さん

**Comment by mahya8585** [comment]
なみきさんから表示名と画像の差し替え依頼が来たので対応する

**Comment by omame1986** [comment]
Android /iOSの比較セッション
に変更する

**Comment by mahya8585** [comment]
@omame1986 ↑はセッションタイトルを「Android/iOSの比較セッション」に変更するってことでいいですかね？
まだ未対応でしたら対応しましょうか？

**Comment by mahya8585** [comment]
えりこさんはLTなので概要なしでおけ。完了。

宇佐美さん再プッシュ完了。もし25日までにリターンなければ登壇者チェンジしたいと思います。

@quwen キャンセルになった場合LTやりますか？

**Comment by omame1986** [comment]
Android / iOSの良いところ発表会のセッションタイトルの変更になります
どなたかついでにできそうであればお願いします

**Comment by omame1986** [comment]
Android /iOSの比較セッションの概要を以下に変更する


何かと比較されがちなAndroidとiOS。
今回は各エンジニアがそれぞれの良いところやちょっと苦労するところを
ショートセッション形式でお話ししていきます。
まだAndroidとiOSを触ったことがない人でも大歓迎です！
アプリ開発の裏側をお話しします！
