### ISSUE TITLE
共催コミュニティLTやりたいコミュニティを募集

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#183]
希望あれば枠は用意する。
共催コミュニティLT連絡を各コミュニティへ通達。
希望あれば登壇者名をもらう。
一般登録してもらう。

**Comment by mahya8585** [comment]
連絡を年内に。

登録は当日まで

**Comment by omame1986** [comment]
開催まで日がないので通達と共にLT時間を伝えようと思うのですが
昨年のKPTを確認したところ今年は1分でいいでしょうか

**Comment by omame1986** [comment]
1分で出した。

**Comment by mahya8585** [comment]
Java女子部・droid girls・GGC・PyLadies 登壇済み。
