### ISSUE TITLE
ご飯発注

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#184]

**Comment by okohs** [comment]
転職DRAFT(リブセンスさん）からのビールスポンサー
- DRAFTビール40本
- 甘いサワー系 80本

**Comment by mahya8585** [comment]
K-Price　おいしい烏龍茶 500ML  500ML
価格（税込）
70円
数量
15本
小計（税込）
1,050円
冷やした商品
15本
希望する
サントリー なっちゃん りんご（果汁２０％）  430ML
108円
5本
540円
5本
希望する
亀田製菓 ハッピーターン  120G
204円
3袋
612円
希望しない
不二家カントリーマアム　バニラ＆ココア　２０枚  20ﾏｲ
409円
5個
2,045円
希望しない
グリコ　クラッツ　ペッパーベーコン大袋(17G×6パック)  17G*6P
324円
3個
972円
希望しない
サンナップ ホワイトプレート（18cm紙皿×10枚入り）  18cm*10ｲﾘ
108円
10袋
1,080円
希望しない
キリン　氷結シャルドネスパークリング 350ml缶  350ML
124円
5缶
620円
5缶
希望する
キリン チューハイ ビターズ ほろにがレモンライム　350ml 缶  350ML
133円
10缶
1,330円
10缶
希望する
サントリー オランジーナ  420ML
92円
10本
920円
10本
希望する
割り箸元禄　20膳  20ｾﾞﾝ
108円
4個
432円
希望しない
 
 
送料(お届け方法：カクヤス配達)
無料
 
 
合計
9,601円

**Comment by mahya8585** [comment]
代引きだよ。

- 当日買うもの
    - [ ] ウェッティ
    - [ ] ゴミ袋

**Comment by mahya8585** [comment]
![2017-01-12 12 50 05](https://cloud.githubusercontent.com/assets/10239748/21876979/27b8ffac-d8cb-11e6-85f0-a3f26c1fd85d.png)
![2017-01-12 12 46 00](https://cloud.githubusercontent.com/assets/10239748/21876985/351ae534-d8cb-11e6-81ff-f75311ca4a1c.png)
