### ISSUE TITLE
フォトスポットを作成する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#19]
- フォトスポットに置くものの作成
  - 物理フォトフレーム
  - 言語別アイテム

**Comment by okohs** [comment]
## 物理フォトフレーム

こんなのどうかな(https://marry-xoxo.com/articles/2367)

## 言語別アイテム

フォトプロップスが良さそう。  
硬めの紙に言語のロゴとかマスコットキャラとか印刷して後ろに竹串なりを貼ればok

**Comment by okohs** [comment]
ボランティアスタッフにお願いしたい

**Comment by okohs** [comment]
余裕があったら

**Comment by mahya8585** [comment]
5000円くらいだと嬉しい
@kanakogohzu ともんちゃんにやってもらおう

**Comment by mahya8585** [comment]
予算組から

**Comment by okohs** [comment]
物理フォトフレームの方は時間があまりないので、もう進めちゃいましょう。

**Comment by okoysm** [comment]
これ良さげ、これにしない？
http://pbw.theshop.jp/items/3215537

**Comment by okohs** [comment]
@kanakogohzu すごいかわいい物理フォトフレーム見つけた！時間もあれなので、これ頼んじゃいます！
デザインとかは任せて！！！！
http://pbw.theshop.jp/items/3215537

**Comment by okohs** [comment]
@kanakogohzu Instagram風フォトフレームはデザイン上がってきました！特に問題なかったので印刷お願いしました。21日発送予定なので全然間に合いそうです。

**Comment by kanakogohzu** [comment]
了解です！:bowing_woman:

**Comment by kanakogohzu** [comment]
手で持つフォトドロップのほうは2千円もあればできそうです！
材料はこちらで購入して領収書もらっておくでいいですか?(近所に100均があるので)

**Comment by okohs** [comment]
@kanakogohzu いいね！とGeek Women Japan♡ってのはセットで物理フレームについてくるので用意しなくて大丈夫です！（仕事終わったらここに画像アップしますね！）

**Comment by kanakogohzu** [comment]
@okoysm おおおありがとうございます！了解です！
Geek Women Japan♡ってついてくるのうれしいですね(｀･ω･´)ゞ

**Comment by okohs** [comment]
@kanakogohzu こちらです！
https://drive.google.com/drive/folders/0B8Q1ejJYGDKhNTZ6Y3ByN0JyREU

**Comment by okohs** [comment]
物理フォトフレーム発送されました。我が家に届きます。

**Comment by okohs** [comment]
本日物理フォトフレーム到着しました。我が家で真ん中くりぬいておきます。

**Comment by okohs** [comment]
## 物理フォトフレーム

作成done.

## フォトプロップス
- Geek Women Japanなフォトプロップスは一つ完成
- 共催コミュニティのフォトプロップスも作る
- 作成作業はボランティアスタッフの人に手伝ってもらう

![20161029_202648](https://cloud.githubusercontent.com/assets/10089070/19837201/157d08fe-9ef8-11e6-80f8-e5de41be3d73.jpg)
![slack for ios upload 1](https://cloud.githubusercontent.com/assets/10089070/19837202/1587d5b8-9ef8-11e6-9c75-caa2651f78bd.jpg)

**Comment by okohs** [comment]
お疲れ様！！！
