### ISSUE TITLE
新年会KPT

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#193]

**Comment by mahya8585** [comment]
このあいだのお店とかで我々の新年会＆KPT&次期カンファレンスに向けての定例会やりましょうかね。
定例MTG代としてGeekWomenJapanのお金から出しますよ

**Comment by omame1986** [comment]
KPTシートver2017つくっておいた

**Comment by omame1986** [comment]
みほ
ごっち
記入済

**Comment by kanakogohzu** [comment]
https://docs.google.com/spreadsheets/d/1prEzgIj_7LyWIy1Y5aVSbG8ZJwbUJZ2PugY0ay-my5g/edit#gid=0
@okoysm @mahya8585 覚えていたら記入プリーズ＆特になければその旨コメントしてくださいな
（既にslackで同じ会話していたらスミマセン）

**Comment by mahya8585** [comment]
記入忘れてました！
ただいまdone

**Comment by kanakogohzu** [comment]
まんべんなくふりかえりできた感じなので、一旦closeしましょう 🌈 
KPTの内容カンファレンスの反省に活かせると良いな〜
