### ISSUE TITLE
新年会参加者記録＠dots.

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#195]
イベント参加IDをdotsに登録する

**Comment by kanakogohzu** [comment]
出席者チェックだん(｀･ω･´)ゞ

**Comment by kanakogohzu** [comment]
@mahya8585 @okoysm @omame1986 
出席していたのに欠席扱いになっている人とかいたらすみませんがチェックお願いしますm(_ _)m

**Comment by mahya8585** [comment]
みんな名前が自由すぎてわかりませんww
大丈夫だと思います〜

**Comment by kanakogohzu** [comment]
ありがとうございます！ではクローズします(｀･ω･´)ゞ
