### ISSUE TITLE
スタッフリードの名前変更

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#197]
http://geekwomenjapan.github.io/agreement.html

**Comment by mahya8585** [comment]
done.
合わせてごっち・みほさんを追加。休会の方を除外

@kanakogohzu twitterわからなかったのでとりあえずGitHub名で載せてます。Twitterのがいいなって感じであればご連絡ください（自分で直してみてもいいよ！練習になるかも

**Comment by kanakogohzu** [comment]
GitHubで 🙆 です 🎉

**Comment by mahya8585** [comment]
ありがとうございます！
