### ISSUE TITLE
コアキャストを倍増させる

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#199]
人が足りてないのでコアキャストを倍増させたい。
「どんな人集めてきたらいいかな？」って相談をされたのでとりあえずこういう人が居たらいいなってのを書いてきます。

### MUST
- Slackでメンション飛ばしたら1週間以内にはレスが返ってくる
- Slack, GitHub, Hangoutが使える（使ったことなくても使えるように勉強してくれる）

### WANT
- Web/紙のデザインスキル
- フロントエンド開発のスキル
- コミュニティでの運営経験
- カンファレンスのスタッフ経験
- 平日の日中に動ける時間が作れる

**Comment by mahya8585** [comment]
- 仕事を振ってもらう(ことももちろんあるけれど)という思考ではなく見つけて持って行く思考の方。もしくは左記をやったことないけどできそうな方

**Comment by okohs** [comment]
たしかにそれMUSTだね。
Wikiに書いてみた
https://github.com/GeekWomenJapan/CoreCastWorks/wiki/%E6%B1%BA%E3%81%BE%E3%81%A3%E3%81%9F%E3%81%93%E3%81%A8

**Comment by kanakogohzu** [comment]
確実に2名は増えた！ということできりが良いので一旦closeします 🎉
