### ISSUE TITLE
託児スペースについて協議する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#20]
- 託児プロフェッサーを置く
- おもちゃなど
- 託児エリアにも中継を

**Comment by mahya8585** [comment]
子育て中の女性エンジニアから雑談ベースでヒアリングした
- 走っちゃだめスペースと多少多目的に遊べるスペースは分けたほうがいい。走っちゃダメスペースには赤ちゃんとか寝かせるようにする。
  - 遊べるスペース・走っちゃダメスペースともに100均とかのウレタンマットが敷いてあるとよい
  - こう考えるとちょっと40人部屋手狭かも？いらないものは極力ほかの部屋に移動させたい。もう一部屋多く取る方がいいかも。
  - けがの可能性のある角には角カバーを。
  - 授乳用の仕切りとかあると嬉しい
- あかちゃんのおむつ替えはマット＋タオルでOK。動き回るためすぐ汚れるので、間にビニールシートを挟んでタオルは替えをたくさん用意しておくとよい
- アニメを流すならディズニーとか男女共通の内容のものを。難しくないやつ。
- お母さんの連絡先は必ず聞いておいて、漏れちゃった、とかのときは即呼び出しできる状況を作っておく

(また思い出したら追記します

**Comment by mahya8585** [comment]
プロを呼んだときの費用感参考。お値段高めですが、会場費が安かった分、こちらに回す余力は十分にありそう。

試しに10：00～17：00託児をお願いした場合の参考値を並べてみます。
託児施設を持ってる企業さんとかにちょっと聞いてみようかな。法人サービスを持っている出張育児サービスしている企業とかもあって、よさそう。
大体10～15名程度のお子様を預かる想定で、20万前後をみておくとよさそう

①あいね
http://www.eine-liebevolle.com/index.php?%E3%83%99%E3%83%93%E3%83%BC%E3%82%B7%E3%83%83%E3%82%BF%E3%83%BC%E3%81%AE%E3%82%B7%E3%82%B9%E3%83%86%E3%83%A0%E3%81%A8%E6%96%99%E9%87%91%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6
子供一人2000円/時間　10名よりイベント出張受付。イベント出張時の金額は書いてないですが、一日約15～20万というところではないでしょうか。

②集英社の育児プログラム
http://www.shopro.co.jp/has/business/event/index.html
値段書いてないが、見積もりしやすそうなので出してみてもいいかも。ここちょっとよさそうって思ってる。

③明日香
http://www.g-asuka.co.jp/corporate/event/
保育スタッフ一人につき2500円/時。スタッフ8名呼ぶとだいたい①と同じくらいの金額。ただし法人向け。

④ポピンズ
https://www.poppins.co.jp/corporate/event/
ここもよさそう。ただし法人向け。金額感は見積もりださないとわからない。が、マイクロソフトが使ってるとかみると結構お値段しそうだな・・・とか思っている（勝手なイメージ）

**Comment by mamix1116** [comment]
・Windows女子部が実績あり。要ヒアリング。託児スポンサーもありかも。
・５社くらい見積もりあり。
・DjangoGirls→PyCon→GeekWomen、とノウハウをためて実施する。

**Comment by okohs** [comment]
RubyKaigiで万葉さんが託児所スポンサーやってる。  
しょこ→旦那にRubyKaigiの託児所偵察してもらう
まあやん→Windows女子部に聞く。

**Comment by Gyori** [comment]
Windows女子部は託児所したわけではなく、スペースを作って遊び道具用意+机を並べてベッド代わりにしただけ、とのことでした。

他も聞いてみてますー。

**Comment by Gyori** [comment]
@okoysm RubyKaigiの偵察ってできましたか？もしよければ万葉さんとRubyKaigiの担当者の方のコンタクト先を教えてくださいー。

Win女子部アドバイスで保育士さんに短期アルバイトをお願いする、と思いましたがちと参加者だったりで金額読みづらくって。一旦経験者に聞いてみたいです。

**Comment by okohs** [comment]
@Gyori 私ではなく主人がですが、偵察できました。が、利用者側じゃないので注意深く見ないとどこにあるのかよくわからないくらい奥まったところだと聞きました。
利用希望者は参加登録時にアンケートに記入し、運営からその後個別にメール連絡との流れでした。  

万葉さんの連絡先はスポンサー一覧にあります。  
RubyKaigiの担当者の方は特につながりありませんが、Twitterを見る限り ‏@shyouhei さんが担当っぽいです。（RubyKaigi運営の方なのは確か）

**Comment by mahya8585** [comment]
@Gyori @mamix1116 さんがついこないだのPyCon2016で託児担当やっています。
今ここに情報共有してもらうようにお願いした

**Comment by Gyori** [comment]
あざます！

**Comment by mamix1116** [comment]
PyConでは、業者さんは、アルファコーポレーションさんに頼みました。
備品の搬入搬出、準備から撤収まで手慣れてて、よかったです。
PyConJPの榎本からの紹介です、と伝えて下さい。
http://www.alpha-co.com/cc_event.html

別室で完全預かりで、保育スタッフが責任を持って預かる場合と、
キッズスペースを作って補助する保育スタッフはいるけど、基本的に親が必ずついて、責任は親が持ってねっていう、やり方がある。PyConでは前者。
両方用意してもいいけど、責任の所在がわからなくなるから、部屋を分ける。
1時間前から搬入。撤収30分程度。全ておまかせ。

月齢、性別、兄弟関係によって必要なスタッフ数が変わる。
10ヶ月男の子、1歳半男の子、３歳姉と１歳弟、の４名を２人の保育スタッフで見てもらった。
募集のやり方を工夫して、調整できるようにしておいたほうがいい。
余裕のある運営を。
預ける側が、親も子も託児慣れしていない場合がある。保育園行ってないし、長時間預けるのは初めてということも。

備品が結構多いです。赤帽で慣れた方が持ってきてくれるけど、台車が入れる搬入経路、搬入スタッフは確保しとく。オリセンは車おけるところが限られるから、事前に確認したほうがいいとおもう。

命を預かるという意識は忘れずに。

**Comment by mahya8585** [comment]
明日連絡
dotsページを早々に立てる

**Comment by Gyori** [comment]
10万以内のイメージ
10人未満ぐらい
- dotsのイベントサイトを立てる
  サイト公開時には条件を記載する
  登録する子供の年齢とか聞く

**Comment by yakitorii** [comment]
突然どうもお邪魔します、 RubyKaigi の方から来ました。
RubyKaigi 託児所担当、ついでに万葉社員の鳥井です。（ https://github.com/GeekWomenJapan/CoreCastWorks/issues/20#issuecomment-249774764 で @shyouhei  さんにメンションが飛んだのでこちらご紹介されました）

RubyKaigi では 
- 会場に30平方メートルの部屋一室を確保
- [ポピンズ](https://www.poppins.co.jp/)さんという業者さんに完全委託
  - 安全管理・おもちゃや持ち込み設備（マット等）の用意 等は全てポピンズさん任せ
  - 持ち込み設備が多いのは PyConさんと同様。会場のほうの担当者様と託児業者の担当者様を早めにメールでつなげて、詳細相談は直接やってもらいました。
  - 9:30-18:00の預かり時間 + 前後の用意 で保育スタッフさん 2名 で 3日間 
  - 月齢、性別等で必要スタッフ数、必要な部屋の広さ等変わるので、事前にお見積りご相談が必要
  - 何かあったときの保険等はポピンズさんが加入済み
  - 「熱が何度以上だと預かれない」等の制限事項がポピンズさんより書面（PDF）でお知らせ頂けますので、託児希望の方にお伝えします。
- 事前申し込み制、会議チケット購入時に希望を聞いて、託児所希望の方に詳細情報+本申込みのご案内、本申込みのあった方のみ登録、という流れでした
  - 結構事前アンケート -> 本申し込みの間に人数が減りました
- 安全確保のため、託児室の場所は公開なし（スタッフにお問い合わせがあった場合、スタッフ同伴でのみ見学可）
- 託児するほどではないが授乳スペースがあると嬉しい、という要望もありました。会場におむつ替え台のあるお手洗いがありましたのでそちらをご案内。

という感じでした、ご参考になれば。
質問等ありましたら @yakitorii までお知らせください。（ twitter: `@yotii23` のほうが反応良いかも）

**Comment by yakitorii** [comment]
追記： 東京RubyKaigi11 というカンファレンスでも託児所案が出たのですが、用意するとしたら本会場の上の方の階の一室しかなく、
会場の秋葉原コンベンションホールさんが「託児所を設けると子どもの騒音でその階を利用する別の団体に迷惑がかかるので許可できない」ということで頓挫しました（代わりに休憩室を設けました）。
先に会場の方にOK条件を聞いておくの大事です。

**Comment by Gyori** [comment]
おぉ、ポピンズさん、ありがとうございます！
アルファコーポレーションさんに見積りとってるところなのですが、試しにポピンズさんにも相見積とってみます。
条件としてはどちらも同じようにみえます。

**Comment by Gyori** [comment]
アルファコーポレーションから見積りきた。詳細確認中
https://drive.google.com/drive/folders/0B0Vs20dDhCZmSmU2bjYzWEdCUHM?usp=sharing

**Comment by Gyori** [comment]
こんな感じのWEBサイトを用意してくれるの含めて12.6万みたいです。
WEBサイトもお願いする形でお願い進めて良いですか？
@mahya8585 
https://cscs.alpha-co.com/event_yoyaku_kihon_form.jsp?E=587799*MVx4q

**Comment by mahya8585** [comment]
面倒は全部お願いしてしまおう。
頼んじゃってください（10人も子供来るか微妙だけど）

**Comment by okohs** [comment]
@Gyori @mahya8585 これって聞いたんだっけ

> 先に会場の方にOK条件を聞いておくの大事です。

**Comment by mahya8585** [comment]
あー聞いてない！ @Gyori 聞いてもらえますか

**Comment by okohs** [comment]
@Gyori 会場OKかこの週末で聞けるなら聞いてほしい。
聞けそうにないなら他のメンバーに振って！
会場の電話番号：03-3469-2525

**Comment by kanakogohzu** [comment]
会場OK出ました〜 🎉

**Comment by Gyori** [comment]
ほんっとすみません！ダッシュで動きます 🙇 
会場確認ありがとうございます！

**Comment by mahya8585** [comment]
@Gyori 
![進捗どうですか](https://github.com/mahya8585/code-review/blob/master/2_shintyoku_question/Krabby_shintyoku.png?raw=true)

**Comment by Gyori** [comment]
まちがいない。電話とメールでプッシュします。申し訳ない！！！
![62132366](https://cloud.githubusercontent.com/assets/1139747/19788708/dbdb5fac-9ce4-11e6-84a6-a9f7f8ec2bd0.gif)

**Comment by Gyori** [comment]
@okoysm すみません、HP上にこちらの掲載をお願いできますか。託児したい方はこれに記載して申込書を送付いただきたいです。
送付先はgeek women のアドレスで良いかと思っています。
よろしくお願いします！！
URL : https://cscs.alpha-co.com/event_yoyaku_kihon_form.jsp?E=622621*N2N9E
ファイル: https://drive.google.com/file/d/0B0Vs20dDhCZmU1BMVTFWLUYyTTg/view?usp=sharing

**Comment by mahya8585** [comment]
@Gyori 
ん？
https://cscs.alpha-co.com/event_yoyaku_kihon_form.jsp?E=622621*N2N9E

このWEBページからの申し込みだけじゃだめってことかにゃ？（=WEBページのURLをリンクする＆メールで送付する）

**Comment by mahya8585** [comment]
把握した。両方ナイトだめななのね。

忘れてくるお母さんいそうだから当日何枚か印刷して会場に置いておこう

**Comment by omame1986** [comment]
dots反映done
参加者へ託児できるよメール配信done

**Comment by omame1986** [comment]
- FB
- Twitter

告知done

**Comment by mahya8585** [comment]
今日31日の２３時までが登録締め切りになっていますが、
そのあとの飛び込みとかはどうですか？
定員割れしてたらオK？

@Gyori

**Comment by Gyori** [comment]
確認します！

**Comment by Gyori** [comment]
飛び込みOK
現在2組予約あり、1組のみ残りありだそうです @mahya8585 

当日は9時頃来ていただいて場所を調整します。

**Comment by okohs** [comment]
お疲れ様！！！
