### ISSUE TITLE
サテライト会場の検討

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#201]
サテライト会場の検討

## 目的
東京のイベントにはこれない地方の人向け

## サテライト会場候補地
spreadsheetにまとめよう

**Comment by kanakogohzu** [comment]
@okoysm これどうするか一回みんなで検討したい感がある 👀 

> 東京のイベントにはこれない地方の人向け

ということだけどの県だと良いんだろう 🤔  💭

**Comment by okohs** [comment]
関西（京都府か大阪府）いいかなーと思っている。
理由：既に女性エンジニアコミュニティがある。開催実績もある。
## 京都での開催実績
Women Techmakers Kyoto
https://connpass.com/event/53277/
はてなの規模がわからないけど、集まった人数で盛り上がれるくらいのキャパあるといいなと思ってる

## 大阪での開催実績
Girls In Tech日本ローンチイベント（これは実際に行った）
ダイキンのテクノロジーイノベーションセンターがすごい良かったよ！（バスか車必須だけど
http://www.daikin.co.jp/tic/about/index.html

**Comment by kanakogohzu** [comment]
良さそう！
個人的には京都すごい良さそうに感じる

**Comment by okohs** [comment]
京都良さそうなのは他にも理由があって、Googleの支援するエンジニアコミュニティGDGも大阪じゃなくて京都にあるからそっちのリソースあるていど使えるのではないかと考えてる

**Comment by kanakogohzu** [comment]
超LGTM😍
コミュニティ同士新たな繋がりもできるし、ちょっと大変だけどトライしてみる価値あり。

ジャストアイディアだけど

- キーノートは中継
- サテライト会場では別途京都コミュニティの人たちに発表してもらう

とかできると良い

**Comment by okohs** [comment]
良いと思うー！そうすると共催コミュニティの負担の種類も前回より変えられるかもー！
前回はセッションを持つっていう結構な重さだったから、今回はサテライト会場支援っていう形もアリだからね！

**Comment by mahya8585** [comment]
Girls in TechとJava Day Tokyoで会えるので、
当日参加できるスタッフでご挨拶＆名刺交換をしてこようと思います。
あわよくばその場でサテライトについてちょっと話を触れてみようかと。

**Comment by mahya8585** [comment]
昨日のJDTで、Girls in Techの方に10月のイベント一緒にやりませんかと打診してあります。大阪サテライトについても打診中
6がつに一度顔合わせてのMTGしましょうって話になっています。

**Comment by kanakogohzu** [comment]
なんかメッセージとかでやり取り進んでいる 👁? 
6月入ったので調整さんしてMTGしましょうかね(｀･ω･´)ゞ

**Comment by mahya8585** [comment]
今のところ何もやりとり進んでないです。
調整さんしてMTGしましょう〜。

面識ある私か @kanakogohzu の少なくともどちらか1名が参加できる日の中で2名以上が参加できる日にしましょう〜

**Comment by okohs** [comment]
Girls in Techは大阪ローンチイベント行ってるから運営の人ひととおり面識あるよー。

**Comment by okohs** [comment]
昨日中継ありのイベントをやったのだけど、全部中継じゃなくてローカルでも何かあると参加して楽しい感じがあった。
せめて懇親会だけでもローカルでやってもらいたい(それを支援するために前回の剰余金を使うのは良さそう)

**Comment by kanakogohzu** [comment]
りょーうかい！その辺諸々相談してきます〜

**Comment by mahya8585** [comment]
イベント見直しのため、一旦クローズ.
GITとは引き続き連絡を取り合って、来年のイベントで支援いただけるようにする。
別チケット発行します
#247
