### ISSUE TITLE
Call for Paperを出す

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#202]
個人からの登壇を募集

## 目的
TBD

## 募集要項
TBD

**Comment by kanakogohzu** [comment]
WEB・SNS担当 の @omame1986  さん @SSL-Kohda ちゃん中心で担当してもらいつつ、初めての試みなのでみんなでサポートしていこうという感じになった 💨

**Comment by mahya8585** [comment]
ざっくりしたタイムスケージュール感？JJUGの運営スケジュールパクってきました。参考までに。

- 〜6月中旬：CfP募集ページ作成
  - 登壇者表記名
  - 登壇タイトル
  - ジャンル
  - レベル感
  - 内容
  - 登壇者写真
  - 遠方支援の有無(交通費支援するのであれば)
- 6月中旬：CfP募集開始
- 7月：CfP応募期間
- 8月：CfP選考＆タイムスケジュール確定
- 9月月初：CfP当選者(登壇者)連絡

**Comment by okohs** [comment]
CfPそろそろやらんとあかんね、
7月応募開始なら作業できそう。

**Comment by mahya8585** [comment]
イベント見直しのため、一旦クローズ
