### ISSUE TITLE
スピーカ事務局->Tmixの件を返信する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#203]
```
上記の際にスポンサードさせていただいたTシャツの増産をしたいとの
お問い合わせを頂戴しております。デザインのデータ等お持ちでないようですので、
念のため石田様のご了承をいただいてからお話を進めさせていただきたく思います。
お忙しいところご面倒をおかけいたしますが、上記について
ご確認とご連絡をよろしくお願い申し上げます。
```
Tmixより連絡あり。

以下MSより

```
Tシャツについてですが、TMIX様のコンプライアンス上、初版の制作を依頼された方に一度許可のご連絡を取る必要があるそうで、
初版を担当された方にTMIX様から連絡が入りますので、その旨をお伝えいただきますようお願い申し上げます。
```

増産・・・？
同じ会社で別デザインだと思っていたんですが・・・
その辺の認識差異も含め明日(8日)返信メールします。

- [ ] MS
- [ ] Tmix

**Comment by omame1986** [comment]
スタッフ枠に申し込みがありました
Tシャツ枚数に余裕をもって作成いただくことは可能でしょうか。連絡ついでにお願いしていただきたいです。

**Comment by mahya8585** [comment]
かしこまりです！
こちらの不足分も調達してもらうようにします。160で良さそう。

@okoysm @omame1986 @kanakogohzu 
カンファレンスと同じデザインで作成することを許可しますか？
別デザインもしくは別色での作成をお願いしますか？

**Comment by kanakogohzu** [comment]
別デザインにしてもらったほうが良さそう 💨 


## アイディア
- MSとコラボってことならMSカラー（青だっけ?）のTシャツにGWJのロゴとか
- もしくはロゴを MS × GWJ みたいに並べてもらって日付とか入れてもらうとか

**Comment by okohs** [comment]
これじゃダメなのだろうか
<img width="683" alt="2017-02-08 18 06 26" src="https://cloud.githubusercontent.com/assets/10089070/22730217/63c0ad56-ee29-11e6-9ed6-7b3468bc5702.png">

**Comment by kanakogohzu** [comment]
LGTM

**Comment by mahya8585** [comment]
同じこと考えてたわw
譲歩してもらえるかわかりませんが（Tmix/博展/MS/Geek Women Japanとプレイヤーも多くなってきてるし）、打診してみましょう。画像作ったんだからイラレ画像あると思うんだよね。

**Comment by mahya8585** [comment]
取り急ぎ、（この後別のスタッフMTGがあり深夜まで対応できなくなるので）
↑のにしない？とMSに打診済み。

- 残タスク
    - Tmixへの返信
    - MS対応

**Comment by omame1986** [comment]
ありがとうございます
スタッフ１名分追加確定で、枚数の調整をお願いします！

**Comment by mahya8585** [comment]
かしこまりです！ 

デザインについて
どうやら完全同じものではなく、MSロゴと合わせたデザインをMSの方も想定されているようです。事務局の方との認識とれ次第Tmixにお返事します

**Comment by mahya8585** [comment]
Tmix 返信done

残タスク
- MSへ枚数の返信

**Comment by mahya8585** [comment]
枚数返信done

デザイン・色も合意済み（ライトブルー・左胸GWJロゴ・袖MSロゴ）
