### ISSUE TITLE
MSコラボイベント告知

### ISSUE THREAD

**Issue by omame1986** [GeekWomenJapan/CoreCastWorks#206]
- FB
- Twitter

3/4のMSコラボイベントの告知業

↓ちなみに11月のカンファレンスの時はbufferを使用したり。自由に。
https://github.com/GeekWomenJapan/CoreCastWorks/issues/137

**Comment by okohs** [comment]
とりあえず第一発はdone.
Bufferは任せた

**Comment by omame1986** [comment]
みきてぃーありがとう❗
