### ISSUE TITLE
アクセンチュア対応

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#207]
Facebookに来ている連絡に対して対応する

GWJ側要望
- 秋のカンファレンスのスポンサー
    - 取り組みの告知を行うことでリクルーティングを求めていると思うが、やり方についてはこちらでハンドリングしつつ慎重に話を進める必要がある

直近の想定フロー

- [x] facebook返信
- [x] 面通しする
- [ ] 慎重なる調整

**Comment by kanakogohzu** [comment]
- 当日の議事録　https://geek-women.slack.com/archives/sponsor/p1488615602000081
- ブレストシート　https://drive.google.com/drive/u/0/folders/0B8Q1ejJYGDKhQWVPdWJCR3JfQ3M

ブレスト内容だけみると、夏くらいにミニカンファやろう〜というノリになっていますが、以下の理由から、**まずは勉強会かセミナーをやってみるというのが良さそう**。で、秋のカンファレンスのスポンサーになってもえたら最高ですね 🎉 

- コアキャスト側のリソースがない
- 秋のカンファレンスの準備に時間をかけたい
- MSイベントが終わったばかりで各コミュニティの登壇者もお疲れの様子


@okoysm @omame1986 @mahya8585 なんか意見ありますか 🤔 💭

**Comment by omame1986** [comment]
概ね話し合って上記と合意なう

開催を「平日夜」にする、とかだとどうだろう。

**Comment by kanakogohzu** [comment]
これどうするか8日に相談したい気持ち

**Comment by kanakogohzu** [comment]
もうカンファレンスの準備始まっていて厳しさあるので、カンファレンスで一緒にお取り組みできたらという感じで 💪 
もし先方からなにか連絡来ていれば教えてもらえますか? 👁  @okoysm 

特になければこのissueは一旦closeしましょう 👾

**Comment by okohs** [comment]
特に連絡きてないから一旦closeしよう
