### ISSUE TITLE
MSイベントのKPT書く

### ISSUE THREAD

**Issue by omame1986** [GeekWomenJapan/CoreCastWorks#208]
ごっち
みほ
記入済

**Comment by kanakogohzu** [comment]
@mahya8585 
気づいたことあったら記入おなしゃす 🙏  🙏 
https://docs.google.com/spreadsheets/d/14e8SKfMoIoyf3Gj7X19lT1kwSg0ByJBtTV6iUFDOYOU/edit

**Comment by mahya8585** [comment]
追記しました！
@kanakogohzu @omame1986 確認いただけましたら本チケット完了でお願いします！

**Comment by omame1986** [comment]
あざました！
