### ISSUE TITLE
新コアキャスト招待

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#209]
仲間がふえるね 🎉 

- [x] 新コアキャストをslackに招待 @mahya8585 
- [ ] それ以外のアカウント発行等 @omame1986

**Comment by mahya8585** [comment]
各個人の登録作業確認のために各スタッフinvite用チケットを別々に発券しました。

- #215 
- #216 
- #217 

@omame1986 本チケット一旦クローズいたしますので、上記チケットの対応よろしくお願いいたします><!!!
