### ISSUE TITLE
子供が参加できるプログラムを作成する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#21]

**Comment by mamix1116** [comment]
・Java女子部でコンテンツ作成プロジェクトをやっている。子ども向けのWSコンテンツを創っている。それを使ってやりたい。

・Dots女子部も、似たような構想があり。

・複数あってもよい。子どもといっても、対象が沢山ある。

・いろんなコミュニティーから集めて、よりよいものをみんなでつくろう。コラボなどもあり。

**Comment by okohs** [comment]
コミュニティに任せる。
