### ISSUE TITLE
ウィメンズプラザ申し込み

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#211]
[東京ウィメンズプラザ＠青山の施設予約内容](https://www.tokyo-womens-plaza.metro.tokyo.jp/reserve/index2.html)  

## TODO
- [x] 書類を @okoysm から受け取る @kanakogohzu 
- [x] 会場抑えられるか問い合わせ・日程は10月〜12月初旬のどこかで @kanakogohzu

## 他カンファレンスの日程
- [10/8 PHPカンファレンス（略してペチコン）](http://phpcon.php.gr.jp/2017/) 
  - ↑去年被ってて友人がかなりこっち行っちゃったのでこの日は外したい
- [10月 楽天のカンファレンス](https://tech.rakuten.co.jp/index.html)
- [9〜10月 DevFest](https://gdg-tokyo.connpass.com/event/38927/)
  - ↑調整できるのでなんとかする
- [10月の終わりか11月の頭を狙ってる JJUG CCC](http://www.java-users.jp/)

**Comment by okohs** [comment]
3/20〜3/31に行う10月の抽選応募内容

## 日程
1. 10/14
2. 10/21
3. 10/15
4. 10/22

## 部屋
7ヶ月前はとりあえずホールだけなのでホールを抑える

## 時間
午前＋午後（9時〜17時）か全日（9〜21時）か。
オリセンは安かったから全日にしたけど今回どうしようか。

**Comment by mahya8585** [comment]
とりあえずホールは全日でいいんじゃないかな。
いくらだか把握していないけれども。
10月早い方が良いと思います(14/15)

**Comment by kanakogohzu** [comment]
14,15　良さそう

**Comment by kanakogohzu** [comment]
進捗：施設予約システムにログインできないという謎問題が発生しているので問い合わせ中

**Comment by kanakogohzu** [comment]
上記の問題解決～

**料金表**
http://www1.tokyo-womens-plaza.metro.tokyo.jp/facilities/tabid/128/Default.aspx

**Comment by kanakogohzu** [comment]
![a](https://cloud.githubusercontent.com/assets/2108951/24189861/f7dcc724-0f29-11e7-835b-a72e1bcf7943.PNG)

- 抽選完了
- 費用20万円くらいです

**Comment by kanakogohzu** [comment]
4/1 10:00に結果がわかってその後予約ができるので、申請作業だけお願いします 🙏 
**手順**
http://www1.tokyo-womens-plaza.metro.tokyo.jp/facilities/tabid/169/Default.aspx

**Comment by okohs** [comment]
10/9無事当選！！！！！
