### ISSUE TITLE
会場スポンサーの検討

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#212]
## 背景
- オリンピックセンターやウィメンズプラザを抑えられるか怪しい (確定ではないが)
- 会場スポンサーを用意して、企業に会場を提供してもらうのはどうか
- ウィメンズプラザの空き状況次第ではあるが、やはめに動く

## やること
- 会場スポンサーありかなしか決める @みんなヽ(=´▽`=)ﾉ
- 会場見学や話がつきそうなところにアポって相談にいく @kanakogohzu

**Comment by omame1986** [comment]
概ね話し合って上記と合意なう。

さらに踏み込むと
例：モノスポンサー、メディアスポンサー等、
前回の守備範囲を決めたスポンサー制を活かして
「会場スポンサー」というのもありではというお話

背景に、前回の振り返りを踏まえて
- 冷暖房の調整がしやすい
- 会場へアクセスがしやすい
- できれば「IT」「女性」といったイメージに近いキレイさ

が本音というのがありました。

以下について、特に重点的に二人( @okoysm  @mahya8585  )の意見を聞きたく思っています。

- ウィメンズプラザもいいけど、「女性」を強調するイメージが強い点はどうか。フェミニン色が強く出すぎるのではないか。（あと希望日に抑えらるか不明）
- 会場スポンサーしてくれる企業がいるとして、企業色に対してどこまで懸念があるか。

どうかなー

**Comment by kanakogohzu** [comment]
会場決まったので一旦closeします(｀･ω･´)ゞ
