### ISSUE TITLE
MSイベントのイベントレポート作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#213]

**Comment by mahya8585** [comment]
とりあえずTwitterに出ていたイベントレポートと登壇者資料をリンクしました。
写真はまだなので昨日GoogleDriveにあげた写真とかを誰かおなしゃす！

トゥゲッターもまだリンクしてません。

その他イベントレポートや登壇者資料ありましたら追加もよろしくお願いします！

**Comment by omame1986** [comment]
写真がいっぱいあるのでドライブにアップします

**Comment by mahya8585** [comment]
とりあえず暫定公開しました。
https://eventdots.jp/eventreport/611429

今後写真や登壇資料が増え次第随時追加ということで
