### ISSUE TITLE
MSイベントの参加者をdotsサイトに反映する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#214]

**Comment by mahya8585** [comment]
https://drive.google.com/drive/u/0/folders/0BzV_v1Mtvy9SdDByXzZmUjRXVEE
参加者リストのCSVをいただきました。
どなたかお時間ある方、dots反映をお願いしたいです！

**Comment by omame1986** [comment]
終わりましたー完了！
