### ISSUE TITLE
さきちゃんコアスタッフinvite

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#216]
- [x]  GitHub オーガナイザマスタ権限付与
- [x] facebookページ管理者権限付与
- [x] Twitter/gmailアドレスとパスワードの共有
- [x] Google Drive共有
- [x] コアキャスト作業案内
- [x] Slackへinvite
- [ ] 現在の進捗共有

**Comment by omame1986** [comment]
- [x] dotsオーナー権限
