### ISSUE TITLE
なつこさんコアスタッフinvite

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#217]
- [ ]  GitHub オーガナイザマスタ権限付与
- [ ] facebookページ管理者権限付与
- [ ] Twitter/gmailアドレスとパスワードの共有
- [ ] Google Drive共有
- [ ] コアキャスト作業案内
- [x] Slackへinvite
- [ ] 現在の進捗共有

**Comment by omame1986** [comment]
- [ ] dotsオーナー権限

**Comment by kanakogohzu** [comment]
@omame1986 すべて対応済みでしたらcloseおなしゃす 🙏  (さっき対応済みと聞いているけど念のための確認です！)

**Comment by kanakogohzu** [comment]
↑まちがいっ
