### ISSUE TITLE
予算組み

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#218]
スポンサー必要な額を割り出す

完了したら↓やる
https://github.com/GeekWomenJapan/CoreCastWorks/issues/227

**Comment by kanakogohzu** [comment]
@mahya8585 予算組みどこかで相談したいです 🙏  
5月くらいに1度もくもく会しますかね 👀  もちろんHangoutでやっても良いです。
問題なければスケジュール調整します。
1~2hくらいかかりそうな感覚でいます。

**Comment by mahya8585** [comment]
日程別途お送りするので、そこで調整させてください！
（日程決まった時点でここに書き込みする方針で！）

#227 
#219 
#228 
#229 

をいっぺんにやらねばならぬーな感じな気がするので、2-3h見てもいいかも

**Comment by kanakogohzu** [comment]
@mahya8585 そうですね、2-3hみておきましょう。そこいっぺんに決まるとみんなもスポンサーへの声掛けとか動けるので最高な感じがします 🎉 

> 日程別途お送りするので、そこで調整させてください！
（日程決まった時点でここに書き込みする方針で！）

合点承知の助(｀･ω･´)ゞ
スケジュール合わせられると思うので、多めにいくつか候補下さい 👯‍♂️

**Comment by kanakogohzu** [comment]
23日にもくもく会する 💃

**Comment by mahya8585** [comment]
https://docs.google.com/document/d/12-sztKmPnszx6GX1X5ks77cFZ4gZPyjot7cQV7yHGFg/edit
にて金額赤裸々に記載中。
めどはたったので一旦クローズします
