### ISSUE TITLE
スポンサーテーブル組む

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#219]
予算のためのスポンサーを得るためにテーブルを組む

**Comment by kanakogohzu** [comment]
スポンサー・事務処理担当 の @mahya8585 @kanakogohzu で進めていきます

**Comment by mahya8585** [comment]
スポンサー規模感的には前回と同じ要領でOKと判断。
ただ、見せ方・そのランクでできることの見直しをする必要あり。
上記残タスクについては以下チケットで対応するため、本チケットはクローズする

- #238
- #228
