### ISSUE TITLE
JDTについて

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#221]
詳細はslack参照。
8日にちょちょっと話せたらいいと思います

**Comment by kanakogohzu** [comment]
(やることがあれば)お手伝いさせてもらう程度で、今回登壇はなしでいいかも?
先方が登壇者呼ぶのにこまっているのなら、こちらとしては誰かコミュニティから探して紹介すると良さそう。誰か登壇したい／できそうな人がいればもちろん登壇OK！

という話をした。

@okoysm どうしましょう?  🤔

**Comment by okohs** [comment]
日程近い && JJUGに連絡が行ってる のでとりあえず厳しいかなーって返す！
向こうが困ってそうだったら探すの手伝おう。そんな感じで返しときます。

**Comment by mahya8585** [comment]
maaya [9:16 PM] 
@syoko JJUGじゃなくてjavajoね！

syoko [9:16 PM] 
さんくす！
Java女子部にいってるならもう話が早いというか、そこだめならJavaエンジニアは厳しいね

maaya [9:18 PM] 
@syoko うん、それでいいと思う
Java女子部は今日か明日受ける形で返信するのでー

syoko [9:22 PM] 
@maaya 受ける形っていうのは誰か人が出るってことだね？

maaya [9:22 PM] 
ですです

syoko [9:23 PM] 
おっけ。なんかまとめて回答してくれると嬉しい

maaya [9:24 PM] 
まとめて回答というのはgeekwomenの方も私から返しちゃってよいってことかな？

syoko [9:24 PM] 
そうそう

maaya [9:24 PM] 
了解した  
geekwomenからも頼まれたよーという程でなんとなく返信しとく



・・・・としていたものの、文章の流れ上
Geek Womenに「コミュニティメンバ」の概念がないのでJavaエンジニアを集めるのは難しいよ、Java女子部に託したよ的な文章にまとめて返信しました。
告知のお手伝いなどについては(スポンサーなどの話も上がっている関係上)OKとして返信しています。

一旦完了にします。また話が膨らみそう(SNS告知お願いみたいな)であれば別途チケット切ってWEB担当のみんなと進めていければと思います。
