### ISSUE TITLE
スポンサー候補リスト作成・声掛け

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#229]

**Comment by okohs** [comment]
現状スポンサーOKともらってるところはGoogleくらい。そのへんの情報Googleドライブにまとめていこう

**Comment by kanakogohzu** [comment]
@okoysm 
やったぁ 🎉 スポンサーランクや予算感については、どのように話しを進めていますか? 👀 


とりあえずシートを作成しました。
https://docs.google.com/spreadsheets/d/10E5Pt4KlY2O5M8PwHoctaHD51pHQ06FvR9BiicbNRQc/edit#gid=0

いったん私と @mahya8585 で、昨年度のを参考にアタックリストを作成して挨拶・声掛けしていくのが良いかしら?
企業の担当者目線(自分は判断する側に立つことのほうが多いので)だと、挨拶メールと一緒に金額も知っておいてさっさと判断したい気持ちがあるので、諸々計算してスポンサーのメニューを確定させてから具体的に声掛けするでも良さそう。

**Comment by mahya8585** [comment]
https://docs.google.com/document/d/12-sztKmPnszx6GX1X5ks77cFZ4gZPyjot7cQV7yHGFg/edit
「スポンサーテーブルの調整」欄を確認の上進めて行く。

まずはアタックリスト作成をGW終わりくらいまでに。

**Comment by okohs** [comment]
スポンサーのドキュメント更新お願いします><
アトラシアンを確定に追加とか。
アクセンチュアは追加になったんだっけ…？

**Comment by kanakogohzu** [comment]
なるほどアトラシアン確定したのか👀
アクセンチュアはまだ話すらしていない状態だと思う。

**Comment by mahya8585** [comment]
とりあえず各自手持ちの企業リストをアップデートしてください

- [ ] @kanakogohzu 
- [x] @okoysm 
- [ ] @SSL-Kohda 
- [ ] @omame1986 
- [ ] @icachan 
- [ ] @quwen 
- [ ] @mahya8585

**Comment by mahya8585** [comment]
リストはできてるのでクローズします。
声かけるするときにまたアップデート
