### ISSUE TITLE
Wi-Fi発注

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#230]
- [ ] 部屋数と参加スタッフ分でいくつ必要か数える
- [ ] 3社くらい相見積

**Comment by okohs** [comment]
@kanakogohzu 相見積もりの見積書のGoogle ドライブリンクを貼って欲しい！

**Comment by kanakogohzu** [comment]
OK見積もりしたら貼っときます🙋

**Comment by mahya8585** [comment]
イベント見直しのため、一旦クローズ
