### ISSUE TITLE
懇親会どうするか決める

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#231]
- [ ] 昨年の出席率を調べる
- [ ] 会場で軽食できるか調べる(どこか具体的に調べる)
- [ ] いい感じのケータリング調べる

**Comment by icachan** [comment]
ちなみに私のおすすめで、寿司ケーキというのがありまして…
http://minayoshi.net/

**Comment by kanakogohzu** [comment]
見ましたw候補に入れましょうw
立食で懇親すると思うので、分けやすいかどうかはちょっとよく見ておきたいところ👀🍣

**Comment by icachan** [comment]
文字とか入れてくれるので楽しめるかなと！分けるには残念ながら包丁が必要ですね。
まさにケーキのように食べる寿司なので！
過去に何度も注文してますが楽しいですよ～候補の一つとしてぜひ♪
他にも色々考えてみまする

**Comment by icachan** [comment]
そうだ！これも明日電話で施設に一緒に聞いたほうが良さそう

⇒会場で軽食できるか調べる(どこか具体的に調べる)
会場のどの部屋でできるかを下図確認しながら聞く
よく懇親会などでケータリング入れるところとか？
視聴覚室が良さそうかな？

http://www1.tokyo-womens-plaza.metro.tokyo.jp/facilities/tabid/125/Default.aspx

**Comment by kanakogohzu** [comment]
http://www1.tokyo-womens-plaza.metro.tokyo.jp/facilities/tabid/132/Default.aspx

> 貸出施設内で飲食はできますか。
会議室内では、匂いの強くないものでしたらお召し上がりいただけます。
ホールでは、配線の関係上、すべての飲食をご遠慮いただいております。
ご了承ください。


> 飲食をメインにした催事で会議室等を使いたい。
申し訳ありませんが、当プラザの会議室等を、飲食をメインとした催事の会場としてお使いいただくことはできません。

という感じらしい

**Comment by mahya8585** [comment]
会場ケータリングなので一旦100人分20万で予算つけました。
進行お願いします。

足りなさそうな場合はお申し付けください！

**Comment by kanakogohzu** [comment]
( ﾟдﾟ)ﾊｯ!

@mahya8585 ドリンク代（1名1杯くらい）込で20万でよかですか？ 👁 
問題なければ　@icachan ケータリング探しお願いしたいです 🙏

**Comment by mahya8585** [comment]
懇親会予算的には20万で良いと思います。
（ケータリングだと多分ドリンクは2-3杯いけると思う）

20万超えそうであれば懇親会費とってもいいですし。
安くすむならそれはそれでよし
目安として掲げる程度でいていただければ良いかと思います

**Comment by icachan** [comment]
人ついてくれるほうがいいですよね？いくつかさがしてみまーす！

**Comment by kanakogohzu** [comment]
@icachan 
いればいいけど高いならついていなくてもOKと思います！
お願いします 🙏

**Comment by kanakogohzu** [comment]
@omame1986 出席人数について、昨年は70名くらい出席しましたっけ…? 🤔 
（ごめんなさい受付していたのに記憶がない…）

**Comment by okohs** [comment]
前回は60人くらい！！
https://geek-women.slack.com/archives/C0HBMG0BS/p1487336226000210

**Comment by kanakogohzu** [comment]
サンクス

@icachan 見積もりしたりする際70名目安で計算してください🙏

**Comment by icachan** [comment]
１ついいなーとおもうところで見積もりもらおうと思うんだけど、時間ってどのくらいになるのかな？👀
ウィメンズプラザは全日レンタルで21時まで？、http://www1.tokyo-womens-plaza.metro.tokyo.jp/facilities/tabid/128/Default.aspx
片付け考えて20時ENDの18時開始２時間ってとこかな？
託児所もいったん18時で見積もってしまったけどそもそもイベントって18時でよかったかしら(´・ω・`)

**Comment by kanakogohzu** [comment]
会場利用、休日なので17時までだ🙃

**Comment by mahya8585** [comment]
イベント見直しのため、一旦クローズ
