### ISSUE TITLE
託児所予約する

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#232]

**Comment by okohs** [comment]
東京ウィメンズプラザが託児所いけるか確認するのも必要だね

**Comment by icachan** [comment]
◆前回依頼した託児所に確認する
⇒どこに依頼したのか？規模感は？
◆ウィメンズプラザに託児所の受け入れを確認する
⇒予約名はどうなってますか？

**Comment by kanakogohzu** [comment]
> ⇒どこに依頼したのか？規模感は？
- [アルファコーポレーション](http://cscs.alpha-co.com/)
- 前回の見積もり→ https://drive.google.com/drive/folders/0B0Vs20dDhCZmSmU2bjYzWEdCUHM
- 10名規模で契約していました〜

> 予約名はどうなってますか？
- 予約情報→https://drive.google.com/drive/folders/0BzV_v1Mtvy9SVEZDUWN2RXVZRWs
- 問い合わせの電話番号：03-5467-1711 

https://github.com/GeekWomenJapan/CoreCastWorks/issues/20
参照元

@icachan 
- 施設へ問い合わせお願いします 🙏 
- 施設側がOKだったら、一度15名規模で見積もりお願いします 🙏  以下2社でお願いします。
   - [アルファコーポレーション](http://cscs.alpha-co.com/) ※昨年カンファレンスとMSイベント時に利用
   - [ポピンズ](http://cscs.alpha-co.com/) ※ruby kaigiで利用

cc @okoysm 
託児所なんですが去年10名で契約していたみたいなんで、いっそう盛り上がることを期待して今年はいったん15名で見積もり出してみます〜 😃

**Comment by okohs** [comment]
託児所契約の見積もりありがとう！了解です。

**Comment by icachan** [comment]
今日こそ電話と思ったら休館日＞＜　あああ明日から頑張る！！！！

質問は託児所団体を15名程度で予定していて、受け入れが可能かどうかっていう点問題ないですか？

**Comment by kanakogohzu** [comment]
- 業者に依頼して託児ルームを設ける予定だが、施設として託児利用可能か？
- オリンピックセンターや他社のイベントで実績はあります
- 人数は、聞かれたら10名前後

というニュアンスで聞いていただけると🙏

もし託児利用禁止と言われたら、どこに規約があるか、文書化されてわかるとこに掲載しれているかマイルドに聞いてください🙏

**Comment by icachan** [comment]
託児確認しました！
会場としては手配しませんが好きに手配OK（申請不要）

２F 保育室を使用しても問題ありません　とのことです。
![img_map2f_l](https://cloud.githubusercontent.com/assets/26278016/25218001/24771228-25e4-11e7-938a-c16e356f7c61.jpg)

…狭そうだけど

**Comment by icachan** [comment]
あでも第一会議室が80名キャパなんで、行けるかもですね。要下見！

**Comment by mahya8585** [comment]
今別イベントでアルファコーポレーション(前回託児お願いしたとこ）と連絡取っているんですが、
アルファコーポレーションさんでは子供1名につき3.3平米〜で広さ計算をするそうです。
人数と部屋の配分の参考までに！

**Comment by mahya8585** [comment]
アルファコーポレーションさんの他、パソナテックさんに相見積もり取らせていただく。

https://docs.google.com/document/d/12-sztKmPnszx6GX1X5ks77cFZ4gZPyjot7cQV7yHGFg/edit
「託児」欄にて。

**Comment by kanakogohzu** [comment]
まとめると
- ウィメンズプラザ託児OKでめでたい
- 15名で見積もりだすぞ
→ アルファコーポレーション（( ﾟдﾟ)ﾊｯ!あいかさんもうやってくれている？）
→ パソナテック（これはまーやさんにお願いしてもOKですか？関係性的にそのほうが早そう感ある）

@icachan @mahya8585

**Comment by mahya8585** [comment]
パソナテック問い合わせ中〜

**Comment by icachan** [comment]
まだですー、ごめんなさい！
実は会社用のPCを入れ替えていて、ぎーくうーめんのGoogleアカウントのログインができなくなっちゃったんだけども、これって誰の携帯で認証してるんでしたっけ。。。

**Comment by icachan** [comment]
日時　10/9(月）　託児時間10:00-18:00
（前後30分を派遣人件費とし、9:30-18:30で計算）
受け入れ児童は15名ほどを想定しておりますが、年齢は未定です

受け入れする施設は東京ウィメンズプラザ保育室（約71㎡）を予定しております、
詳細は下記リンクを参照ください。

http://www1.tokyo-womens-plaza.metro.tokyo.jp/facilities/tabid/126/Default.aspx


こんな感じでめーるしてみた！！ポピンズもだしてみる？

**Comment by icachan** [comment]
http://www1.tokyo-womens-plaza.metro.tokyo.jp/Portals/0/images/facilities/twp_hoiku.pdf

ってか今見たんですけどめちゃくちゃ充実した保育室ですね、さすがウィメンズプラザ。。。
人さえいればよさそうなので、前回より安くすみそうな予感も。

**Comment by okohs** [comment]
保育室のPDFもメールで伝えると良さそう！
設備周りとか持ってこなくていい(→安くやる)
とかないかなぁ…

**Comment by kanakogohzu** [comment]
そこも含めてパッケージなきがするので厳しい気もするけど、問い合わせの時に言ってみる価値はありそう💘

**Comment by icachan** [comment]
そですねーでもまだメールの返事がなく！月曜日でんわしてみます！

**Comment by kanakogohzu** [comment]
電話大変なのでできたらで大丈夫です🙆

**Comment by icachan** [comment]
やだー二日前に見積書きてたｗだいぶ高いけど、前回は２人体制だったのね。
＞今回は既存の託児室を使用予定のため、備品・玩具代金を通常の50％としております。
とのこと！
[見積書.pdf](https://github.com/GeekWomenJapan/CoreCastWorks/files/1066291/default.pdf)

ググルドライブどこに配置していいかわからずとりあえずマイドライブに保存したけど、適切な場所おしえてくださいまし＞＜

**Comment by mahya8585** [comment]
@icachan 
受注しない旨を先方に連絡お願いします。
連絡後クローズしてください

**Comment by icachan** [comment]
受注しませんメールしましたのでCloseでしゅ
