### ISSUE TITLE
ステッカー発注する

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#233]

**Comment by kanakogohzu** [comment]
@okoysm 
そろそろなくなってきたそうなので、前回と同じところで発注依頼しちゃおうと思います 😄 
特に問題ないですよね? 👀 

@icachan 
しょこさんOK出たら、
https://github.com/GeekWomenJapan/CoreCastWorks/issues/61 を参考にして300枚発注をお願いします 🙏 
そんなに急ぎではないけど、他の勉強会やイベントに持ち込んでもらえたりすることを考えるとささっと作成するといいことありそう 😄

**Comment by okohs** [comment]
発注依頼しよう！JJUGのCCCとかに持っていきたいなー

**Comment by mahya8585** [comment]
@kanakogohzu @icachan 
とりあえず早めに作成開始しましょう〜
目指せJava Day Tokyoかな。
前回の情報、まーやが持ってますので、slackにてやりとりしましょう。

**Comment by icachan** [comment]
承知ですです。＃61見て途中までやってみたけども、わからなかったまま動けていなかったので、明日までにちょっと進めますので、また質問させて下さい！SlackというのはまーやさんとごっちさんにPrivate　Message?

**Comment by mahya8585** [comment]
#conference-order みたいなチャネル作って良いです！(コアスタッフみんな入れておいてください !)
そこで発注系の業務の話し合いしましょー

**Comment by icachan** [comment]
［注文No］B71442_S001
［納　期］ 7営業日
［お支払方法］クレジットカード
［名　称］フィルム素材ステッカー(耐水)／白塩ビ
［お客様管理用名称］GeekWomenJapan
［色　数］フルカラー
［サイズ］24平方センチ以内
［オプション加工］強粘着/ 光沢PETラミネート/ 40パス以内/ １枚四角カット
［枚　数］300枚

**Comment by icachan** [comment]
届いた＆配布開始したからクローズ？

**Comment by kanakogohzu** [comment]
💪
