### ISSUE TITLE
スタッフ用パーカーを作る

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#234]

**Comment by kanakogohzu** [comment]
- https://tmix.jp/ にパーカー50枚で見積もりだしてる中 🌀

**Comment by kanakogohzu** [comment]
見積もり届きました
目安としてこれくらいです。


https://tmix.jp/products/Daluc-DM106

```
■お見積り金額: ￥237,600 （約 ¥4,752 ／1点）　※税込

■明細:
御見積番号：43049S01
商品：定番ジップパーカー ｜50 枚
色数：表0 色 印刷なし ｜裏2 色 全面 
```

**Comment by mahya8585** [comment]
(前回の余剰金の使い方の方針を決める必要があるけれど）
検討可能範囲のように思います。
@kanakogohzu 予算案計算するときに考慮するようにしましょう〜！
他のイベントで割引券拾ってくればもう少し安くいけるかも。

**Comment by kanakogohzu** [comment]
> 予算案計算するときに考慮するようにしましょう〜！

そうしましょう！

割引券ありがたい！あと、もしモノスポンサーになっていただくことで割引していただけるならそうしていきたい 👕

**Comment by mahya8585** [comment]
https://docs.google.com/document/d/12-sztKmPnszx6GX1X5ks77cFZ4gZPyjot7cQV7yHGFg/edit
「前回のあまり金の使い道案」で検討中。
#201 完了次第、作成可否について最終ジャッジ。

基本的にはサテライト会場(が立つのであれば)サテライト会場の支援を優先。
そうなった場合はまたTシャツになるかも。

**Comment by mahya8585** [comment]
イベント見直しのため、一旦クローズ
