### ISSUE TITLE
WEBまわり引き継ぎ

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#236]
## 引き継ぎ
- リポジトリ
[GeekWomenJapan/geekwomenjapan.github.io](https://github.com/GeekWomenJapan/geekwomenjapan.github.io)

## たくらみ
- Jekyll導入して誰でも更新できるようにしたい

**Comment by mahya8585** [comment]
@SSL-Kohda 特に現段階で質問事項がなければ、適宜作業issue作成の上、本チケットのクローズをお願いします！

**Comment by SSL-Kohda** [comment]
Jekyllって何って状態ですが。
それは、ゆっくり調べます！
