### ISSUE TITLE
李さんコアスタッフinvite

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#237]
- [ ]  GitHub オーガナイザマスタ権限付与
- [ ] facebookページ管理者権限付与
- [ ] Twitter/gmailアドレスとパスワードの共有
- [ ] Google Drive共有
- [ ] コアキャスト作業案内
- [x] Slackへinvite
- [ ] 現在の進捗共有

**Comment by okohs** [comment]
これお願いしますー

**Comment by mahya8585** [comment]
李さんからリターンなく、進められぬ状態です。。。
もう一度連絡して見てリターンなければクローズしたいと思います

**Comment by mahya8585** [comment]
お返事がないため一旦クローズします
