### ISSUE TITLE
イベント告知カードを作成する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#239]
告知用チラシの代わりの名刺サイズカードを作成する

ラクスルのお急ぎ便（3営業日発送）を予定（100枚800円＋送料190円）

- Geek Women Japanの文字
- ロゴ
- HPアドレスとQRコード
- イベント日時

**Comment by mahya8585** [comment]
俄然センスがないことがよく分かった。コメント求。
納品の関係上今日・明日で依頼をかけないといけないのでできれば早めにおなしゃす！
https://drive.google.com/drive/u/0/folders/0B2jun1de3VScT0JTNWd1Sk81aTQ

**Comment by mahya8585** [comment]
【案1】
表
![default](https://cloud.githubusercontent.com/assets/10239748/25521691/9838c258-2c3b-11e7-88a0-d8d2b9c79491.png)
裏
![default](https://cloud.githubusercontent.com/assets/10239748/25521692/9a995bb6-2c3b-11e7-84a6-4f6aa048195b.png)

【案2】
表
![default](https://cloud.githubusercontent.com/assets/10239748/25521713/ab4507b2-2c3b-11e7-8c95-ff3688b4ebd7.png)

裏
![default](https://cloud.githubusercontent.com/assets/10239748/25521723/b3ff0074-2c3b-11e7-9641-4380321de33b.png)


＊両方とも裏のミント線はもう少し細くなります（デザインテンプレート上のはみだし用も塗り込んでいるため（塗り足し部分）

**Comment by quwen** [comment]
表に情報が多い気がするので、QRコード・Twitterアカウント・Githubは裏に書くのはどうでしょうか？

配色は白地の[案2]の方がロゴにあってる気がします。上下縁取るのも可愛いと思います。
私は下のサイトの配色見本よく使ってます（ちょっと色違った...）
http://www.color-sample.com/colors/2eddc3/

**Comment by kanakogohzu** [comment]
- 配色2が良さそう
- みきちゃんのいう通り裏にSNS情報裏で良さそう
- 表にウィメンズプラザの住所書くとちょっと嬉しい

**Comment by mahya8585** [comment]
![default](https://cloud.githubusercontent.com/assets/10239748/25600210/831ea362-2f1d-11e7-9689-3af953220619.png)
![default](https://cloud.githubusercontent.com/assets/10239748/25600211/8320e00a-2f1d-11e7-8eee-455dfc7c54cc.png)

**Comment by mahya8585** [comment]
以下slack議事録

```
icarium
QRコードこの色で読めるかどうかってのが確認したいです！たぶん全然大丈夫かなーと思いますけど＞＜
あとはここからは好みの問題かもしれなくて、詳細は～の一行はなくてもいいかな？と思いますが皆様いかがかな？

maaya
隙間空いたから入れてみただけなので、削除しましょうね～
QRコードは一応読めたけど印刷色によっては確かに厳しくなる可能性ありますね・・・・何色にしようかな・・・

隙間確かにです！！そしたらアクセスを下に配置したらバランスよくなる？（アッ行動早すぎる！さすがです！それです！！！）
ぐぐるとカラー印刷普通にアリだし今時のスマホで読めないことないと思うのですが、ちょっと淡い色なので念のため確認したいと思ったり！
web画面上はQR行けました！
が、印刷は試し刷りできないのでよくわかりませんｗ
Accessと同じ色にしてみるか・・・

miki 
東京ウィメンズプラザが2回あるのでどっちかでいいと思います！
上の「東京ウィメンズプラザ 」の説明として、住所を添えるイメージではいかがでしょうか？
あんま見れなくてごめんなさい！

maaya
なるほど
ではAccessだけに変更してしまいます！
いそがしいところありがとう～
QRコードも念のため色の濃い方で行きたいと思います。
存在感はありますがちゃんと読み取れる方が大事ですしね
はっちゅうかけるー
```

**Comment by mahya8585** [comment]
![default](https://cloud.githubusercontent.com/assets/10239748/25601244/98373fa4-2f25-11e7-9db9-143a050b257b.png)
![default](https://cloud.githubusercontent.com/assets/10239748/25601245/98389426-2f25-11e7-95e0-19a28ac66fe2.png)

**Comment by mahya8585** [comment]
[注 文 日]    2017/05/02 11:07:43
[注文商品数]  1
[お支払い方法]  クレジットカード
[お支払い金額]  1,061円
内訳:
　[1705028923-01]  商品代金：800円

　注文合計:       　　　　　　800円
　────────────────────────
　送　　料:  　　　　     　　　　　　190円
ポイント利用：　　　 　　　            -8円
　────────────────────────
　お支払合計金額:     　　　　　  982円
　消費税　　　　:     　　　　　  79円
　ご請求合計金額:     　　　　　  1,061円

（◆進行状況：データご入稿待ち・入金確認済）
 [商　　　品]　名刺
 [仕　　　様]　名刺 通常サイズ 両面カラー マット紙 220kg
 [出　荷　日]　受付日確定から3日以内


----------------------------------------------------------------

購入・入稿済み。
GW前でちょっと時間かかるかも？来週半ばには発送されるはず。
きっとまにあう。

**Comment by mahya8585** [comment]
超早かった。
ただいま入稿確認完了しまして、印刷フェーズ開始しました。ちょっとだけお急ぎ便つかったので、来週半ばには届きそう。
先方製本版(?)↓
![default](https://cloud.githubusercontent.com/assets/10239748/25604312/75dcbf0c-2f3d-11e7-904b-b66920e90f8a.png)

**Comment by icachan** [comment]
じゃ、こっちもクローズしちゃいます♪
