### ISSUE TITLE
会場のホール料金振り込み

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#240]
7/11までにホール利用料金109,600円を東京ウィメンズプラザの口座に振り込む。
会議室などの利用料は当日（要確認）

**Comment by mahya8585** [comment]
@kanakogohzu @mahya8585 
今年のイベントは会場スポンサーを募って、小さいものに変更することにしました。
ゴッチさんキャンセル作業お願いしても宜しいでしょうか！

（キャンセル料などかかるようでしたらご共有ください。振り込みに行きます)

**Comment by kanakogohzu** [comment]
おけおけ🙋
もしキャンセル料あったとしてもそんなにかからないと思います😘

**Comment by kanakogohzu** [comment]
キャンセルできた
キャンセル料金かからなさそう 🎉 
(支払期日もまだだし当然か)
