### ISSUE TITLE
当日配布用パンフレット作成

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#242]
去年前日入稿だったので今年は余裕持って作りたい。
早めに作れば他のイベントとかに置けるので便利！

## 去年書いた内容（＋欲しい内容）
- ロゴ
- タイトル
- 日時
- 会場名
- ハッシュタグ
- 注意事項
- おすすめランチスポット（QRコード）
- タイムテーブル（タイトルのみ）
- タイムテーブルの詳細へのリンク（QRコード）
- 懇親会会場名
- スポンサーロゴ（Diamond, Saphireのみ)
- アンケートへのリンクQRコード
- 会場案内図

**Comment by mahya8585** [comment]
イベント見直しのため、一旦クローズ
