### ISSUE TITLE
CfP選考方法をきめる

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#243]
完全に運営で決めるか、JJUGとかScalaMatsuriみたいに参加者の投票も受けて最終的に運営で決めるかどうしよう。
個人的には今回は初めてだからとりあえず運営内で相談にしたい。

**Comment by mahya8585** [comment]
継続して来年に向けて作業を進める

**Comment by mahya8585** [comment]
一旦クローズ
（次回イベントの時に改めて考える
