### ISSUE TITLE
タイムスケジュールを作成する

### ISSUE THREAD

**Issue by kanakogohzu** [GeekWomenJapan/CoreCastWorks#244]
- タイムスケジュールを作成する
- 色んな議論の土台になるのでとりあえず仮で作成する
- 作業場https://docs.google.com/spreadsheets/d/1JLe8CLolST7rZIp9E7D3Hm8rW0B5OQI2hKVNHv9U6ZA/edit#gid=0

**Comment by icachan** [comment]
作成ありがとう！！！！！！
アルファコーポレーションに託児所の再見積もり頼むけど、
準備・片付け込みの時間じゃないよね？託児利用が1100－1630よね？

**Comment by kanakogohzu** [comment]
これまだ下書きなんだ紛らわしくてごめんなさい🙏
タイムスケジュールは完成したら誰かもう1人くらいにレビューもらって確定としたい🙏
しばしお待ちを🙇🙇🙇

**Comment by icachan** [comment]
daijoubu!
arigato!

**Comment by mahya8585** [comment]
こちらイベント開催見直しのため、一旦作業自体見直し。
一旦クローズします
