### ISSUE TITLE
ネームタグの発注をする

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#25]

**Comment by okohs** [comment]
みほさん

**Comment by mahya8585** [comment]
8月中にデザインを決める

9月発注

**Comment by okohs** [comment]
余裕があったら印刷したい
余裕がなかったらそのまま受付で渡すwww
デコる場所置いても面白いかも・・・
詳細は9月

**Comment by mahya8585** [comment]
13で決定
ラクするで発注予定
300枚で

**Comment by omame1986** [comment]
[sample13.pdf](https://github.com/GeekWomenJapan/CoreCastWorks/files/513551/sample13.pdf)

**Comment by okohs** [comment]
![namecard_logo](https://cloud.githubusercontent.com/assets/10089070/19151314/fb337aae-8c06-11e6-887d-8f4864072314.png)

**Comment by omame1986** [comment]
Googleドライブ>CoreCast>素材>名札

**Comment by okohs** [comment]
@omame1986 第二版としてGoogle Driveにアップロードしました。
アウトライン作成が漏れていたのと、不要な図形が入ってしまっていたので削除しました。
これで入稿問題ないと思います。

**Comment by omame1986** [comment]
あざす！入稿します

**Comment by omame1986** [comment]
ケースの方は以下で検討中
1028円(50枚入り) × 6  = 6,168円

https://www.amazon.co.jp/%E3%83%8F%E3%83%94%E3%83%A9-%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E7%94%A8%E5%90%8D%E6%9C%AD-%E5%90%8D%E5%88%BA%E3%82%B5%E3%82%A4%E3%82%BA-50%E6%9E%9A%E5%85%A5-TKNEPM50WH/dp/B00H6YZ6RK/ref=pd_lpo_229_tr_t_3?ie=UTF8&psc=1&refRID=SN9TQ11610C5FJSF4QNN

**Comment by omame1986** [comment]
[ネット印刷の raksul [ラクスル]｜名刺、チラシ…激安で印刷.pdf](https://github.com/GeekWomenJapan/CoreCastWorks/files/522258/raksul.pdf)

**Comment by omame1986** [comment]
入稿前の確認ＰＤＦが出ました
[1610126077_01L.pdf](https://github.com/GeekWomenJapan/CoreCastWorks/files/527409/1610126077_01L.pdf)
これでよければ印刷にすすみます

**Comment by mahya8585** [comment]
LGTM

**Comment by omame1986** [comment]
出荷予定日
10/22

**Comment by omame1986** [comment]
ケースの方は来週到着予定

**Comment by omame1986** [comment]
届いたよ
名札ケースの方
![kimg1737](https://cloud.githubusercontent.com/assets/17662702/19436382/b7582418-94aa-11e6-990e-77617aa42048.JPG)

**Comment by omame1986** [comment]
![maaya8585](https://cloud.githubusercontent.com/assets/17662702/19829838/796bb388-9e26-11e6-95c2-781003f6521f.jpg)

![okoysm](https://cloud.githubusercontent.com/assets/17662702/19829845/829da9d4-9e26-11e6-914a-c42ce9906493.jpg)
