### ISSUE TITLE
DevFest 託児関連の話を進める

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#250]
予算は多分大丈夫。部屋が余っているか怪しい
DevFest側と要相談。

**Comment by kanakogohzu** [comment]
- 会場は託児利用の実績ありで無問題そう
- 多分借りられる
- @omame1986 が見積もりだしてくれて、費用的に問題ないかオーガナイザーチームに確認中

**Comment by kanakogohzu** [comment]
- 親御さんが迎えに来たときの本人確認をどうするか @omame1986 と考える

**Comment by icachan** [comment]
お疲れ様でした！学び
