### ISSUE TITLE
DevFest クラウドクロスセッションについて進行する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#251]
- [x] 人集め
- [ ] 調整

**Comment by kanakogohzu** [comment]
devfest グループの #2017_wtm_cloudにて進行中 🛤
内容も詰まってきていい感じ
当日は @mahya8585 に代わり @kanakogohzu が担当します

**Comment by kanakogohzu** [comment]
#2017_wtm_cloudにて進行中

**Comment by icachan** [comment]
お疲れ様でした！こどもかわいい
