### ISSUE TITLE
DevFest キャリア系セッション枠の進行をする

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#252]
- [x] 人集め
- [x] 調整

**Comment by kanakogohzu** [comment]
#mail にて進行中！！！！！！！！！！！
@icachan 頼む！！！！！！！！

**Comment by kanakogohzu** [comment]
devfest グループの #2017_wtm_cloudにて進行中 🛤 
内容も詰まってきていい感じ
当日は @mahya8585 に代わり @kanakogohzu が担当します

**Comment by kanakogohzu** [comment]
資料作成もしていただいていて進んでいる様子
引き続き @icachan 頼む

**Comment by icachan** [comment]
お疲れ様でした！面白かったしとてもよかった！
