### ISSUE TITLE
DevFest MR女子部クロスセッションを進行する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#253]
~~- [ ] セッション形式~~
~~- [ ] クロス先選出~~
- [ ] 調整

**Comment by kanakogohzu** [comment]
登壇者決定、 @icachan の方で進めてる。進捗は #mail で。
登壇者さんがSlackよりメールの方がらくとのことでそっちでやってます。
@icachan なんか書いておくと良さそうなこと合ったら書いておいて下さい 🙏

**Comment by icachan** [comment]
おっそれはMRじゃなくｋてキャリアやな

SlackにMR枠召喚中ですー

**Comment by kanakogohzu** [comment]
頭のなかで、入れ替わってるーーーーーーーーー？

**Comment by kanakogohzu** [comment]
ということで間違いでした🙇

**Comment by kanakogohzu** [comment]
進んでる

**Comment by icachan** [comment]
お疲れ様でした！Bプランは大事！
