### ISSUE TITLE
DevFest 休み時間用スライドの作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#254]
- スライドのトップにだけWTMのロゴのせてコラボ風
- GWJとはの説明
- 会場の諸注意
- 次回イベントのお知らせ
- スタッフ募集
- ２分くらいのもの

作成はgoogleスライドで

**Comment by kanakogohzu** [comment]
@icachan 
- https://github.com/GeekWomenJapan/CoreCastWorks/issues/255 が決まったらその内容入れてくださいな 🕺 
- 作り始めるタイミングはまかせます 🗓

**Comment by kanakogohzu** [comment]
@icachan 会場決まったのでそろそろやりますかね

**Comment by icachan** [comment]
https://docs.google.com/presentation/d/1u4-t8ZDQUqvqaL2mvWXj2oRWC-zLRksGmQbZOxrBUGE/edit?usp=sharing
とりあえず２枚作った、ここを編集場所とする！

**Comment by icachan** [comment]
型だけできた！あとで画像とか追加していく！

**Comment by icachan** [comment]
スケジュールは1スライド１紹介みたいな感じでつくってみた！
https://docs.google.com/presentation/d/1u4-t8ZDQUqvqaL2mvWXj2oRWC-zLRksGmQbZOxrBUGE/edit?usp=sharing

ちなみにあんざいさんの紹介文薄そうだけどフォローしたほうがいいかな？しょこさんオファーだっけ？
LINEとXRも薄いのでいま調整中、いっしょにまとめてしんめたるさんに更新依頼かけるつもり

**Comment by okohs** [comment]
@icachan あんざいさんのフォローはウチじゃないけど、薄いから概要とか写真とか出してもらった方が良さそうやね！
コミュニティ紹介とのギャップが気になる

**Comment by icachan** [comment]
お疲れ様でした！使わなかったｗ
