### ISSUE TITLE
新年会会場を確定させる

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#255]
- 1月の15-19日を候補
- 12か19を第一候補

1. ｵﾗｸﾙ(maaya)
1. ｻｲﾎﾞｳｽﾞ(gocch)
1. 21cafe (gocchi)

**Comment by kanakogohzu** [comment]
> 1月の15-19日を候補
 > 12か19を第一候補

@mahya8585 この条件で都合つくかオラクルさんにお手すきで聞いてみて下さい 🙏 そしたらdevfesでも告知出来て良さそう。
日程は会場都合で決めましょう 🤚

**Comment by mahya8585** [comment]
「oracle様会場をお借りできませんでしょうか」というタイトルでgeekwomen@で調整開始しました。
遅くなって申し訳ないです。。。
進捗ありましたら更新します

**Comment by kanakogohzu** [comment]
メール見れてまするありがとうございます！
進捗してて良さそう。devfest終わったら意識を傾けます… 🙏

**Comment by mahya8585** [comment]
新年会無事終了
クローズします
