### ISSUE TITLE
Geek Women の銀行口座を作成する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#26]
書類は完成してるので、ゆうちょに持って行って審査を受ける。

**Comment by mahya8585** [comment]
http://harutama.hatenablog.com/entry/2013/07/05/011343
http://www.tecking.org/archives/3589
http://www.tecking.org/archives/2622

まずはwebページに団体規約ページの作成をする。
（ページ作成についてはioのissueとして別途作成する)

**Comment by mahya8585** [comment]
http://blog.hnsm.lolitapunk.jp/?eid=909

ゆうちょだと団体名でいけるらしい。これにする

**Comment by mahya8585** [comment]
CoreCast/規約系 ディレクトリに叩きを作成。(団体規約/団体規約会員名簿)

@satomyumi @NahoInuyama @mamix1116 @sd-ts1017 
レビューお願いします。指摘事項あればSlackかドキュメントに直接コメントください。

**そしてレビュー完了した方から団体規約会員名簿にお手数ですがご自身の情報の追記をお願いします。**

**Comment by mahya8585** [comment]
【残タスク】
- [x] web掲載用の文言作成 -> webページ作成隊へ依頼
- [x] 上記団体規約と会員名簿の印刷
- [x] 印鑑の準備(100均でOK代表姓のものでGeekWomen用に別途用意)
- [x] 身分証明書の準備(免許とかでOK）
- [ ] 団体の過去の発行物
  - [x] New Years Party のイベントページプリントアウトしたもの
  - [x] アドベントカレンダーページプリントアウトしたもの
  - [x] HPを印刷したもの←間に合えば
  - [x] Geek Women Japan × Geek Girls Carrot × エンガジェット電子工作部のイベントページプリントアウトしたもの
    - http://engadget-girls-linking.peatix.com/

**Comment by mahya8585** [comment]
資料不備で返却されてしまったのでｗ
連休明けにワンモアチャレンジ

**Comment by mahya8585** [comment]
平日に再チャレンジしに行く余裕が今のところないので、個人の使ってない口座を使うことにします

**Comment by mahya8585** [comment]
明日午前中いけそうなので再チャレンジ（これでだめならきょんさんへの連絡はいったん個人口座にします

**Comment by mahya8585** [comment]
銀行口座をゲットした。
後ほどうちわに情報展開いたします。
すでにNew Years Partyの余剰金入金済。
このあときょんさんにも連絡します

**Comment by mahya8585** [comment]
きょんさん連絡済

**Comment by okohs** [comment]
できた
