### ISSUE TITLE
夜の懇親会の運営について協議する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#29]

**Comment by mahya8585** [comment]
教室でそのまま懇親会はできません #5 
学内でやるのであれば、以下の場所でケータリングパーティが可能です。
- 薩埵ホール(外堀校舎6・7階）
  - 870名ホール
  - 室料一日45万くらい(半日利用で25万も可能)
- スカイホール(ボアソナードタワー26階)
  - 250名ホール
  - 室料一日21万くらい
- スカイラウンジ(ボアソナードタワー26階)
  - 50名エリア
  - 室料一日5万程度

**ただし、学校休業日は原則AM8:00-PM06:00までしか教室のレンタルができません。**
**のでもし近くでケータリング会場をとれるのであれば、懇親会については別の場所を検討したほうがよさそう**

**Comment by okohs** [comment]
オリセンの場合、レセプションホールが良さそうだったけど11/3は空いてないので、
他の場所（近いし新宿？）とかを抑えたほうが良さそう

**Comment by okohs** [comment]
8月のMTGで決める

**Comment by okohs** [comment]
10月に入って大体の人数見えてきてから詳細詰める。
場所は新宿あたりで確定

**Comment by okohs** [comment]
9月のMTGで決める

**Comment by mahya8585** [comment]
外部会場で開催する
本チケットのゴールを以下のようにする
- [ ] 会場決定
- [ ] 会場予約

**Comment by omame1986** [comment]
### 懇親会

11/3 (木) 19:00～22:00
 [Caffice](http://www.caffice.jp/)カフィス
TEL:03-3356-1567 

住所
- 東京都 新宿区 新宿 4-2-23 新四curumuビル 2F 

交通手段
- 新宿駅南口から徒歩5分
- 新宿三丁目駅　E6出口直結
- 代々木駅から徒歩6分
- 新宿御苑駅から徒歩8分
- 新宿三丁目駅から288m

設備
- 全席電源あり
- フリーwifi
- 有線マイクあり
- プロジェクターなし

最大人数
- 70～80人

貸し切りにあたって
- 最低保証額として25万円
- 1人4000円のコース。（計算上は63人いれば保証額25万は満たせることになる）
- 時間制限は3時間。
- バイキング形式
- 立食。すわれるところもある。
- キャンセルは2週間前まで。(10/20) 予約しているけれど、本決まりの場合もこの日までに連絡したい。

**Comment by Gyori** [comment]
近場でワイワイできるところを探してみる
場所だけ借りてケータリングでも良い

イメージ: 2,000円/1人 

20万円ぐらいは少なくとも懇親会フォロー費用に回せそう

※場所だけ貸してくれるスポンサー企業とかいるとありがたい

**Comment by omame1986** [comment]
https://spacemarket.com/spaces/wrgxmfkkispifyi1/rooms/h2_cVh3rTKrQWpil
今のところここぐらいしか…
駅から徒歩の場所が分かりづらそうだし、11月の夜の懇親会ではちょっと寒そうかな…という不安がある。
また、レンタル時間について
〇土日・祝日
9：00～11：00

とあるが11/3の予約ボタンは19:00-22:00も有効
祝日処理されてないのかな？と土日もみたが有効
ちょっと全体的に情報が乏しいのでお問合せするしかなさそう

**Comment by mahya8585** [comment]
お問い合わせ&料金見積もりお願いできますでしょうか！

@Gyori @kanakogohzu 余裕あれば合わせて検索お願いします！私もちょっと探してみるよ

**Comment by Gyori** [comment]
近場の企業が無いんだよなぁ・・・もちょいあたってみまー

**Comment by omame1986** [comment]
現時点で参加表明が７６人。
対して現時点で挙がった会場は70-80人と70人までのもの。
会場の規模を大きくして考えなおした方がいいかもしれません

**Comment by kanakogohzu** [comment]
90人前後で入れる場所を探すほうが安全そう…? 👀

**Comment by omame1986** [comment]
規模(70-100人で検討。立席時。)とアクセス（新宿含み）と予算（場所だけで１５万くらい？）に見合ったケータリング用イベントスペースが見つからない。
厳しい。
新宿イベントスペースあるけどやはり広いとこは高い。

**Comment by omame1986** [comment]
２つ目のとこ、お問合せ中。
見積もり料金は19:00-22:00の基本プラン（要は場所だけ）で
税込価格 ￥34,020

予約リクエストなげると既にキャンセル料が発生するので、今のフェーズはお問合せのみ状態。
（電話番号なし）
質問事項は
・祝日は9：00～11：00とあるけど、19:00-22:00でもおｋ？
・入口閉められる？夜冷え込まないかしら？
・最大キャパ何人ですかねぇ
といったところ。
返事が遅いようならもう予約リクエスト投げましょうか？
以下キャンセル料について。今だと(2)の50%に引っかかる。

（1）正式予約成⽴〜ご利⽤ 31 ⽇前までにキャンセル受付：ご⼊⾦額の 30%
（2）ご利⽤⽇の 30 ⽇前〜15 ⽇前までにキャンセル受付：ご⼊⾦額の 50%
（3）ご利⽤⽇の 14 ⽇前〜当⽇までにキャンセル受付：ご⼊⾦額の 100%

**Comment by mahya8585** [comment]
一通り色々考えた＆調べた結果、やはり↑の代々木八幡が良さそう。
@okoysm が家近いらしく立食にすれば70人超えてもいけるのでは？と。

「場所を移動する」とすると人が減ることも予想されるので、ここでいいんじゃないかなー。

@omame1986

**Comment by omame1986** [comment]
ＨＰのスケジュールみると懇親会の時間かわりました？
20:00-22:00の想定でしょうか
ケータリングの配置など、準備の時間も入れて19:00から抑えようと思いますが
撤収作業のことも考えると
23:00まででよいでしょうか
4時間で見積もり料金は税込価格 ￥42,000

**Comment by omame1986** [comment]
サービス料も含みこのお値段で予約リクエスト送信中
45,360
- 11/3
- 19:00-23:00
- 場所のみ

**Comment by mahya8585** [comment]
そうすると、ごはんが約25万くらいで手配できそう。

@omame1986 1つ相談なんですが、ごはんケータリング発注場所、1つ見積もりもらってきてもいいですか。
今回個人スポンサーしてもらうJJUG会長の会社でケータリングやってるので、スポンサーしてもらったお礼も兼ねて、予算が合えばここにお願いしてあげたい。

GTUGで一度使ったんだけど、かなり女子ごのみのケータリングくるし、良い気がする

![slack for ios upload](https://cloud.githubusercontent.com/assets/10239748/19425619/8f759cc2-946f-11e6-8961-d72d57e0bbeb.jpg)

**Comment by mahya8585** [comment]
@omame1986 ごはん持ち込み規定について詳細をお店に問い合わせよろしくおねがいしますー

**Comment by omame1986** [comment]
ひどい。返信きた。
・基本プラン（要は場所のみ）は営業時間外のみ
・営業時間中はパーティープランにしなきゃだめ
・一人6000円ビュッフェ形式

どうします
キャンセルもできる

**Comment by omame1986** [comment]
キャンセル

**Comment by omame1986** [comment]
http://www.kaigishitu.com/detail/00200953001/004/
ここも検討中
ただし最低10時間以上確保とあるため
場所代で120,000かかる
一応空いているかお問合せしておきます

**Comment by omame1986** [comment]
- 11/3 空いてる
- 10時間でなく、最低６時間以上でできるよう交渉してくれる？模様 。会場代の見積もりが72,000 + 税
- ケータリングアルコールありの場合、汚されたくないので指定のケータリング業者さんにしてもらいたい
- 指定の業者：[ダイヤモンドドリームダイニング](http://www.partytimes.co.jp/company)
- プランはなんでもいい。
- 一人ケータリングの人が付くような形になるらしい

**Comment by omame1986** [comment]
近いなら見学にきて、その場でいろいろと話して決めたいような模様だった
予約とって見学にいって交渉したほうがよさそう＆安く良い条件だしてくれそう

**Comment by omame1986** [comment]
[南新宿から徒歩6分コース](https://www.google.co.jp/maps/dir/%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%8B%E8%B0%B7%E5%8C%BA%E4%BB%A3%E3%80%85%E6%9C%A8%EF%BC%92%E4%B8%81%E7%9B%AE%EF%BC%93%EF%BC%90%E5%8D%97%E6%96%B0%E5%AE%BF%E9%A7%85/%E3%80%92151-0053+%E6%9D%B1%E4%BA%AC%E9%83%BD%E6%B8%8B%E8%B0%B7%E5%8C%BA%E4%BB%A3%E3%80%85%E6%9C%A8%EF%BC%91%E4%B8%81%E7%9B%AE%EF%BC%96%EF%BC%90%E2%88%92%EF%BC%91%EF%BC%91+%E6%9D%B1%E4%BA%AC%E8%88%88%E7%94%A3%E6%9C%AC%E7%A4%BE%E3%83%93%E3%83%AB/@35.6843358,139.6989119,18z/data=!3m1!4b1!4m13!4m12!1m5!1m1!1s0x60188ccee342caf5:0x40426b134de8b41!2m2!1d139.698661!2d35.683543!1m5!1m1!1s0x60188ccf8724d395:0x1304ef0a514ec3d8!2m2!1d139.7012289!2d35.6855218)

**Comment by mahya8585** [comment]
↑とともにここも詳細聞いてみるといいかも
https://www.hotpepper.jp/strJ000650935/

貸切の相談結構柔軟にやってくれそうなきがする。
https://docs.google.com/spreadsheets/d/1SVPem9V-3vvLeo8GKSPf5_HxOIGbsmtOa94j2pvzIDo/edit#gid=291895140
見積もり見る限り30万くらいは出せそうなので、一人3000円に納めてもらえれば成立できそうです。
人数100人に満たなくても30万で払う額を固定してしまえば良いので。
↑の会議室とこちらで詳細見積もっていただけますでしょうか！

@omame1986

**Comment by okohs** [comment]
確かにPRONTO柔軟！120人で貸切予約したら最終的に170人に成っても対応してくれた（神田店）

**Comment by okohs** [comment]
西武新宿の方だけど・・
http://r.gnavi.co.jp/e781301/map/

**Comment by omame1986** [comment]
西新宿プロント
- 最低金額が20万7200円
- これは70人で一番お安い2960円のコースにした場合と同様になる
- [7品 スタンダードコース3H飲放付](https://www.hotpepper.jp/strJ000650935/course_cnod03/201611031900_rpn30/)（ビールもカクテルある一般的なものらしい）
- キャンセルできｒのは一ヶ月前まで。なのでまだ予約入れれていない。ここにするなら早めに抑えねば。
- 着席時80人。立席時に100人くらい。
- 仮に100人だと29万6000円となる。ギリ予算内…？まだ備品買ってないけど。

**Comment by mahya8585** [comment]
@omame1986 いいんじゃないかな。2960円のコースで確定しちゃっていいと思います。
人数はいったん70名で申し込みしておいてもらえますか。
立食形式で壁に椅子を並べておいてもらうといいと思います。

人数が増加する場合、何日前までに連絡いれればよいか先方に確認をとっていただけると助かります。

> 【誕生日・記念日に】コースご予約で★誕生日の方に、プロントオリジナルケーキをプレゼント♪
> これって1stAnnibersaryとかでもプレゼントしてもらえるのかな・・・

**Comment by omame1986** [comment]
担当者が14:00-出勤らしいので
18:00に折り返してもらう予約

**Comment by omame1986** [comment]
西新宿PRONTO、70人で抑えました
人数の変動は2日前まで。
ただし10-20人増える場合は一週間前に言ってほしい。
ケーキはなんの記念日でも可能だが5人くらい用。
お支払は当日で。クレカも可能。
担当者イマイさん

**Comment by omame1986** [comment]
100人に変更

**Comment by omame1986** [comment]
19:30から3hに変更

**Comment by mahya8585** [comment]
19:30開演か19:30会場なのかかくにんをお願いします。 @omame1986 

22時終焉

22:30完全撤退

**Comment by okohs** [comment]
お疲れ様！！！！
