### ISSUE TITLE
アフタヌーンパーティについて協議する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#30]
- おやつ代は無料にしよう

**Comment by mahya8585** [comment]
ケータリングを入れたパーティは通常教室では禁止です。　#5 
場所移動するのも後半のセッションに影響でそうなので、
各部屋にお菓子を配布して休憩タイム、くらいにした方がよいかもしれません。
（教室内でお弁当食べる程度であればOKのため。）

**Comment by mahya8585** [comment]
http://sweets-novelty.jp/

**Comment by okohs** [comment]
晴れたら隣の公園とかでやっても良さそう

**Comment by okohs** [comment]
会場の関係で開催できないのでdone.
