### ISSUE TITLE
共催コミュニティの定義を決める

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#32]
何をしてもらうことで共催とするか定義
3月末まで

**Comment by okohs** [comment]
# コミュニティに求めること
- 告知・CfPへの参加・参加呼びかけ
- 連絡したらちゃんとレスポンスが来ること
- 告知→イベント当日の参加・Geek Women Japanが共催するイベントの告知・カンファ- 当日までの告知（スタッフとか）

# コミュニティに提供できるもの
- パネル・ブースが用意できます。LTとか含め何かしら宣伝できる場所を提供
- 共催コミュニティとしてHPに掲載
- HPリンクします！
- 参加費：コミュニティにつきn名まで無料（パネルなら１名、ブースなら２名とか）
