### ISSUE TITLE
プレmeetupを行う

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#33]
- スピーカー
- 共催コミュニティ代表
- スポンサー代表

を集めて説明会兼顔合わせmeetupを行う

**Comment by mahya8585** [comment]
10月後半に実施したい

**Comment by okohs** [comment]
遅くても10月の頭にやらないとまずい

**Comment by mahya8585** [comment]
10月頭までに開催
開催日は次回MTGできめます

**Comment by okohs** [comment]
9月ちゅうに10/14でdots.が使えないか確認する
スポンサーの状況が厳しかったら、コミュニティだけでもいいかも！

**Comment by mahya8585** [comment]
とりあえずOPST会場押さえました。
19:00-

**Comment by okohs** [comment]
@mahya8585 これ10/14にやるってこと案内しなきゃだね

**Comment by okohs** [comment]
はい無理。次はやりたいね
