### ISSUE TITLE
撮った写真の掲載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#42]
掲載方法悩み中。
最終的にはイベントページとフェイスブックページにリンク貼りたいと思う。

**Comment by mahya8585** [comment]
とりいそぎ手持ちの写真を追加しました。
@mamix1116  登壇者写真を追加お願いします！その他良さげな写真あれば！

**Comment by mamix1116** [comment]
Google Driveへ
