### ISSUE TITLE
@satomyumi のコアキャスト追加作業

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#45]
- [x]  GitHub オーガナイザマスタ権限付与
- [x] facebookページ管理者権限付与
- [x] Twitter/gmailアドレスとパスワードの共有
- [x] コアキャスト作業案内
- [x] Slackへinvite
- [x] 現在の進捗共有
- [x] dots.オーナー権限付与

**Comment by okohs** [comment]
- GitHubの権限付与はinviteした。承認待ち
- Facebookページの権限付与やSlackへinviteするためにメルアドとFacebookアカウント確認中
