### ISSUE TITLE
GitHub.ioをブラッシュアップする

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#48]

**Comment by okohs** [comment]
サブ→しょこ

**Comment by mahya8585** [comment]
https://github.com/GeekWomenJapan/geekwomenjapan.github.io/issues/7

にて運営規約ページのたたき作成済み

**Comment by okohs** [comment]
5月頑張る・・・！

**Comment by okohs** [comment]
一通りブラッシュアップ完了。  
残りのタスクはgithub.ioのリポジトリにてIssueを切る。  
以下が実装済み。
- [トップページ](http://geekwomenjapan.github.io/)
- [運営規約](http://geekwomenjapan.github.io/agreement.html)
- [Code of Conduct](http://geekwomenjapan.github.io/conducts.html)
