### ISSUE TITLE
開催場所を決定する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#5]
候補
- http://www.civi-c.co.jp/conferenceroom_t.html
- http://tokyo.re-rental.com/shinjuku/detail.html

**Comment by mahya8585** [comment]
大学に確認

**Comment by okohs** [comment]
スポンサーに声かける前に大学で実施するのか貸会議室を利用するのかは決めておく

**Comment by mahya8585** [comment]
取り急ぎ卒業校へ打診のメールいれてみました

**Comment by mahya8585** [comment]
法政大学を第一候補で動き中
http://www.hosei-web.jp/event/04.html

**Comment by mahya8585** [comment]
多分立地的には外堀校舎が最高。
3階（4-5階も同じ構成なのでどれでもいいけど）の305以外をまるっと貸し切りとかできたらいいなーと思っている
http://www.hosei-web.jp/event/05/gf03.html

ちょっと通路が狭いかも・・・？下見で様子をみたい。

**Comment by mahya8585** [comment]
- [x] 飲食禁止とあるが、利用中の飲み物飲むのもだめかな？（カンファレンスで飲み物飲めないの結構きついと思う）
- [x] 部屋移動タイム、300人一斉に動くことを考えると通路せまい？
- [x] 休憩室とかコミュニティエリアとか遊び場とかお子様遊び場とかの部屋も下見で要検討
- [x] 下見時に金額も併せてきちんと見積もること
- [x] 椅子移動できる部屋とできない部屋をきちんと確認しておく
- [x] アフタヌーンパーティをどういう形態でやれるか、下見時にイメージ・検討しておく
- [x] 外堀校舎が立地的にはわかりやすいが、部屋の並びとしては富士見坂校舎がそこそこ良いと思われる（が、場所がわかりづらいのが難点）要検討してくる。
- [x] 写真をとって、 @satomyumi @mamix1116 がイメージしやすいように資料を集めてくる

**Comment by satomixx** [comment]
## 施設
- [x] 入場時・移動時とかに混雑を少なくする迂回路があるか？
- [x] 休憩スペース・リフレッシュスペースはもてそう？
- [x] 控室に使えそうなスペースはある？
- [x] 建替工事の騒音は問題にならない？

## 設備
- [x] トイレのキャパシティは足りそうか
- [x] 授乳出来る場所ある？
- [x] wifi環境はある？
- [x] 備え付けの椅子は窮屈感はない？
- [x] 子供用トイレや子供が親と一緒にトイレする為の設備ある？

## アクセス
- [x] 最寄り駅から迷いそう？

## 確認事項
- [x] 別フロアのトイレも使える？
- [x] 例えば男性トイレを臨時で女性用に使えたりする？
- [x] プロジェクターは無線で繋げる？
- [x] 飲酒は許可があればOKの様だけど、飲食も許可があれば大丈夫だったりする？
- [x] 飲食はどこでならできる？
- [x] 「物品の販売や陳列は出来ません」とあるが、ステッカーとかフライヤーとかは置いていいの？
- [x] プロジェクターにMBAとかMBPを繋ぐためのコネクターは提供される？

**Comment by okohs** [comment]
- [x] 大学の教室でよくあるこのタイプの椅子、小学生以上じゃないと座れなさそう(前方は普通の椅子だからそこを親子席にする？) 
- [x] 305, 306, 307は広さの割にスクリーン小さいが、後方席用のプロジェクタ&スクリーンは借りれそうか
- [x] 学外団体貸与規定の第７条に人員変更の際は連絡とあるが、どこまでのレベルで連絡するのか。
- [x] 学外団体貸与規定の第13条(1)の特殊設備って何を指しているのだろう。例えば、キッズルームを作ったり、プロジェクターとか置いたりしてはいけないかな？
- [x] 郵送等による備品の事前代理受領と前日入構両方できないとなると、スタートの時間は遅く設定せざるをえない？

**Comment by okohs** [comment]
- [x] キャンセル料確認

**Comment by mamix1116** [comment]
- [x] 仮押さえができれば、部屋を気持ち多めに抑えてきてほしいです
- [x] 本予約はいつまで？キャンセルはいつまで？キャンセル料が発生するのはいつ？

**Comment by okohs** [comment]
小さなめの教室*4欲しい
- 登壇者控え
- スタッフ控え
- キッズスペース
- スポンサーブース？（ちょっとちっちゃいかも。フライヤー・写真・ステッカー部屋なら十分）

休憩専用スペースはいらなさそう。
ロビー広いし、スポンサーブースで遊んでー！

**Comment by okohs** [comment]
スポンサー部屋は専用にしない（人こない）

**Comment by okohs** [comment]
小さめの教室で登壇は厳しそう。ハンズオンならちょうどよさそう！

**Comment by okohs** [comment]
通路の狭さ→外濠校舎の場合、305の出口を一部塞げば通路は確保できそう。
小さめの教室の前の廊下が狭いので、305から出る人を防ぐ

**Comment by okohs** [comment]
外濠校舎4Fと繋がっている富士見校舎3Fに女子トイレ多数あり。
4Fメインでイベントやってトイレたくさん確保したい

**Comment by okohs** [comment]
椅子移動できる部屋とできない部屋をきちんと確認しておく
→小教室のみ可能。中・大教室はむり。

**Comment by okohs** [comment]
授乳できる場所はキッズスペースに布はって作る or 多目的トイレ

**Comment by okohs** [comment]
wifi環境→Geek Women側で準備する必要あり。
男子トイレを女子トイレに→むり
椅子の窮屈感→結構ゆとりある。でも列の真ん中には入りづらいので、そこはアナウンスで対応。（中教室）
最寄駅から迷いそう？→市ヶ谷からなら大丈夫。飯田橋からだと難易度高い。
(出口間違えなければなんとかいける。Google Map使っていけばなんとかなる。（川向いに法政大学ってかいてある建物あるからそれと間違えやすいかも？？？？）。飯田橋の東西線・大江戸線・南北線は難易度高いかも。有楽町線の人は飯田橋ではなく市ヶ谷で降りることをお勧めする。駅員さんに聞けばいけるけど・・・)

**Comment by okohs** [comment]
別のフロアのトイレ→使えます
プロジェクタは無線？→有線
プロジェクター用のコネクタは？→登壇者・スタッフで用意する(多分VGA)

**Comment by okohs** [comment]
椅子座りづらそう？→座りづらそう。膝の上or 横に普通の椅子を並べて端っこに座ってもらう。
キッズルーム確認＆椅子対応向けで、参加登録の時に子供連れorNOを聞く。
305, 306, 307のスクリーン問題→305は後方用ディスプレイあり。306, 307は一番後ろからでもスクリーンの文字が見えるレベル。（ただし文字を大きめにお願いします！と登壇者には伝えておく）

**Comment by okohs** [comment]
仮押さえ→今からでも可能っぽい。来年度大学が使う予定のところはすでに押さえられているので、外部のイベント用の空きを確認。
- [x] 11/26, 12/3の教室空き状況を確認する。

**Comment by okohs** [comment]
- [x] メイク直しスペースありそう？

**Comment by okohs** [comment]
ここまでのTODO一回まとめる。

# 飲食
- [x] 飲食禁止とあるが、利用中の飲み物飲むのもだめかな？（カンファレンスで飲み物飲めないの結構きついと思う）
- [x] アフタヌーンパーティをどういう形態でやれるか、下見時にイメージ・検討しておく
- [x] 飲酒は許可があればOKの様だけど、飲食も許可があれば大丈夫だったりする？
- [x] 飲食はどこでならできる？

# 契約
- [ ] 下見時に金額も併せてきちんと見積もること
- [ ] キャンセル料確認
- [ ] 仮押さえができれば、部屋を気持ち多めに抑えてきてほしいです
- [ ] 本予約はいつまで？キャンセルはいつまで？キャンセル料が発生するのはいつ？
- [ ] 11/26, 12/3の教室空き状況を確認する。

# 規約
- [x] 「物品の販売や陳列は出来ません」とあるが、ステッカーとかフライヤーとかは置いていいの？
- [x] 学外団体貸与規定の第７条に人員変更の際は連絡とあるが、どこまでのレベルで連絡するのか。
- [x] 学外団体貸与規定の第13条(1)の特殊設備って何を指しているのだろう。例えば、キッズルームを作ったり、プロジェクターとか置いたりしてはいけないかな？
- [x] 郵送等による備品の事前代理受領と前日入構両方できないとなると、スタートの時間は遅く設定せざるをえない？
- [x] ギャラリー・廊下にものを置いていいか(スポンサーのフライヤー、受付等)

# トイレ
- [x] 子供用トイレや子供が親と一緒にトイレする為の設備ある？
- [x] メイク直しスペースありそう？

**Comment by okohs** [comment]
中教室は各席に電源タップついてる！電源不足解消！

**Comment by mahya8585** [comment]
### 飲食
- ペットボトルの飲料はOK
- ケータリング不可
  - 薩埵ホール・スカイホールはケータリングOK
  - 薩埵・スカイであれば酒もOK
- お昼時間にお弁当程度あればお部屋でもOK

### キャンセル料
- 会議室案内所で確認

### 物品販売について
- フライヤー配置OK（お金が出てくる販売をしなければOK)

## 使い方について
- wifi程度であればOK
- 05教室前のピロティはポスターセッションとかで使ってOK
- 前日搬入について
  - 基本はダメ。設備対応などHUにお願いすればOK
  - 前日に一部屋抑えてあればOK

**Comment by mahya8585** [comment]
撮影写真
https://drive.google.com/open?id=0B2jun1de3VScaXBpSmJSbW5udU0

**Comment by mahya8585** [comment]
#20
にも書きましたが、子供部屋からもの全部出したいので、もう一部屋小部屋をかりよう。
見積もり表に追記しておきます。

**Comment by okohs** [comment]
結論：法大は借りれなさそう
- 11/1以降の空き状況：3/19のみ
- 土曜日はすべて授業日のため貸し出し無し
- そもそも試験とかじゃなければ貸せない可能性がある

**Comment by mahya8585** [comment]
東京大学の方にお借りできないかご相談のメールを打ちました。
GeekWomenの送信済みメールボックスご確認ください

-> 先生経由でないとレンタルが難しいとのこと。

**Comment by mahya8585** [comment]
その他大学で一般貸出をやっている大学一覧。手当たり次第行ってみるか・・・
できれば女子大とかでやれるとサイコーだよねぇ
- 東京工芸大学
  - http://www.t-kougei.ac.jp/guide/extension/usage/
- 明大中野キャンパス
  - https://www.meiji.ac.jp/kanzai/6t5h7p00000hiwpg-att/a1428996144648.pdf
- 学習院女子大学
  - http://www.gwc.gakushuin.ac.jp/about/facility_rent.html
- 明示学院大学
  - http://meijigakuin-s.co.jp/shisetsu.html

**Comment by mahya8585** [comment]
@sd-ts1017 @satomyumi @mamix1116 @NahoInuyama 

ウィメンズプラザよさそう。が、
- 団体登録が必要
- 4月に11月の会場の抽選を募集している

ため、やるなら早急に動いて4月末までに会員登録＆11月の抽選に参加したい。

http://www1.tokyo-womens-plaza.metro.tokyo.jp/facilities/tabid/125/Default.aspx

**Comment by okohs** [comment]
4月末までの会員登録いけそう？

**Comment by mahya8585** [comment]
http://nyc.niye.go.jp/category/facilities/center/

こちらも団体登録が必要なんですが、JJUGが団体登録してあるとのことなので、団体名借りて登録が可能です！

http://nyc.niye.go.jp/users/center.html
120名や80名の部屋をとるのが難しそうなんですが、小さな部屋をたくさんとるのは可能です。
うまいこと運営できないかな？

11月3日にすると40人部屋4つ5つもちゃんととれそう300人ホールもとれる。

**Comment by mahya8585** [comment]
- AM 300人ホール
- PM 120_2 , 80_2, 40_1, 20_2
  - 120: コラボ部屋
  - 80: ショートセッション, ブース
  - 40: 託児
  - 20: staff+荷物

## 午後の想定としては4Fの左側総なめ

見積もり
- 300 AM  = 18600
- 120 PM/N \* 2 = (10200 + 11000) \* 2 = 42400
- 80  PN/N \* 2 = (6400 + 7000) \* 2 = 26800
- 40 AM/PM/N = 3000 + 3800 + 4000 = 10800
- 20 AM/PM/N \* 2 = (2600 + 3000 + 3200) \* 2 = 17600

116200円///

細かい部屋もうちょっと増やしてもいいかも

**Comment by mahya8585** [comment]
借りれるかどうか別としてJJUGの担当の方にメールを送っておきました。
geekwomenアドレスをCCに入れているので、ご確認ください

**Comment by mahya8585** [comment]
オリンピックセンター抑えました。

![center_4f](https://cloud.githubusercontent.com/assets/10239748/15695505/d0c0962c-27e2-11e6-8e9c-d8f2a4791f67.jpg)

【上の見積もりからの変更点】
- 20人部屋廃止 -> 40人部屋を3つ確保
- 120人×2 -> 120人と160人
- 300 AM = 18600
- 160 PM/N = 14200 + 15400 = 29600
- 120 PM/N = 10200 + 11000 = 21200
- 80 PN/N \* 2 = (6400 + 7000) \* 2 = 26800
- 40 AM/PM/N \* 3 = (3000 + 3800 + 4000) \* 3 = 32400

概算計：128,600円

（もう一個法政大学の情報学部の学部行事として会場を抑えられないか、SeaserConの運営の方に聞いてみてもらっています。）

**Comment by okohs** [comment]
ありがとう！！！オリセン確定したら下見したいね。

**Comment by mahya8585** [comment]
```
本文書に記載された利用規約（以下「本規約」という）を修正することなく承諾するという条件の下で、所定の申請手続きを完了した団体（以下「利用団体」という）へ、イベント開催のために本学が所有する施設を無償で貸与する。
```

まじか

**Comment by okohs** [comment]
会場費まさかの無料！？！？

**Comment by mahya8585** [comment]
法政アウトだったのでオリセンに確定！
wikiに記載しておきます。

チケットクローズ
