### ISSUE TITLE
GMailとSlack連携

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#50]

**Comment by mahya8585** [comment]
不要なDMを全部送信停止にしたいな・・・各アカウント気づいたら停止させるようにしよう

**Comment by mahya8585** [comment]
とりあえず通知設定完了。自動通知がきたらチケットクローズする。
あと、Twitterとか思い当たるDMは全部削除したらクローズする（その後も何かDM来れば都度停止対応）
