### ISSUE TITLE
カンファレンス規約を作る

### ISSUE THREAD

**Issue by mamix1116** [GeekWomenJapan/CoreCastWorks#54]

**Comment by mamix1116** [comment]
#カンファレンス規約

## キャンセルとキャンセル料

## お支払い

## 領収書

## 参加制限

カンファレンスへの参加は全額お支払い頂いた参加者のみとさせていただきます。未就学児は〜

## 義務

Geek Women Japanは、直前の通知により、イベントプログラムの延期、キャンセルまたは、変更をする権利を有します。イベント延期の際も登録は有効です。カンファレンスがキャンセルされた場合、お支払い頂いた全額を返金いたします。返金責任金額は、カンファレンス登録にてお支払い頂いた金額が上限となります。

## 写真撮影、録音、録画

撮影、録画、録音され、メディアによって取材されます。本イベントへのお申し込みをもって、写真、画像、映像、録音、または引用された言葉がGeek Women Japanのウェブサイトやプレスリリース、広報資料、ソーシャルメディア等に無報酬にて使用されることをあらかじめご了承下さい。また、すべてのネガ、ポジ、印刷物、映像、録音、デジタル再生の所有権は、Geek Women Japanに帰属します。

**Comment by mamix1116** [comment]
↑こういうの。

**Comment by okohs** [comment]
これ出来上がり次第運営規約に書いておきます

**Comment by okohs** [comment]
http://geekwomenjapan.github.io/agreement.html
