### ISSUE TITLE
3月Staff MTG

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#57]
【Agenda】
- [x] 共催コミュニティ定義を決める
  - [x] 求めるもの
  - [x] こちらから提供できること
  - [x] 声かけと募集の仕方
  - [x] 第一声かけ期限
  - [x] 以後のコミュニティ数上限
  - [x] コミュニティとの連絡方法
- [x] 銀行口座のスタッフ名簿について
  全員揃ってないけどとりあえず作るよ。
- [x] 会場へ電話係の決定
- [x] HPとりあえずエイヤーで公開しよう
- [x] ロゴ急務
- [x] ボランティアスタッフ募集要項そろそろ決めないとなので叩き作成を誰か

**Comment by okohs** [comment]
銀行口座→２人集まったから、とりあえずまあやんが作るよ。

**Comment by okohs** [comment]
会場へ電話係の決定→しょこがやるよ

**Comment by okohs** [comment]
HPとりあえず公開→
- 団体規約
- コアキャストメンバーの名前/Twitter/Facebook載せる
- Twitter/Facebookアカウント載せる
- お問い合わせはこちらでGeekWomen@メールアドレス

**Comment by mahya8585** [comment]
- なほさんに確認を取る
- まーや友達に聞いて見る
- ココナラに頼んじゃう

の順番で進める
できれば4月頭に、遅くとも4月末までにクリアする

**Comment by okohs** [comment]
- 求めるもの/こちらから提供できることは#32に記載
- 声かけと募集方法→初めにNew Years Partyの共催コミュニティに声かけて、それ以降はGoogle Formで登録してもらう（まあやんさくせい）

**Comment by mahya8585** [comment]
4月頭に声かけ開始できるようにします

**Comment by okohs** [comment]
コミュニティスポンサー上限(仮定)
- パネル*6
- ブース*6
- LT_6 (3分。ランチ_3とディナー*3)

**Comment by okohs** [comment]
コミュニティとの連絡
- GeekWomenJapanのメール
- 各コミュニティ代表向けのFacebookグループ（仮）
