### ISSUE TITLE
ボランティアスタッフ募集要項を決める

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#58]

**Comment by okohs** [comment]
4月にやる

**Comment by mahya8585** [comment]
- 事前準備 + 当日運営
- 当日運営のみ

の2種類募集

**Comment by okohs** [comment]
dotsに立てる。

**Comment by okohs** [comment]
何を手伝ってもらうか？を決める

**Comment by mahya8585** [comment]
## 当日
- ゲストコントロール
- 受付
- 託児室受付とか回す人
- 各部屋付き タイムキーピングと司会業

**Comment by mahya8585** [comment]
当日と前日準備のみでおけ

**Comment by okohs** [comment]
事前MTGは必要。あとは前日に搬入手伝ってもらうかも

**Comment by okohs** [comment]
ドレスコード：赤い服

**Comment by okohs** [comment]
ボランティアスタッフは7人応募あり。とりあえず分担させてみて、足りなかったらもう少し聞く
https://docs.google.com/spreadsheets/d/1eBy5IzubGf42psC6bC-B78NeD267y4ccX2HkiINvgJw/edit#gid=1607503046

**Comment by okohs** [comment]
ボランティアスタッフの募集要項までがこのissueなので一旦クローズ。分担決めとかMTGは別のissue切る
