### ISSUE TITLE
共催コミュニティ登録フォームを作成する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#59]
共催コミュニティ登録ようのGoogleformを作成し、配布。
- 代表メールアドレス
- 代表氏名
- 団体正式名

などなど

**Comment by okohs** [comment]
- 6月中にフォームつくる
- 7/4までに公開 7月末まで募集
- Google Form担当：@okoysm

**Comment by mahya8585** [comment]
@okoysm よろしければGoogleFormURLをwikiに記載しておいてくださいな～

**Comment by mahya8585** [comment]
【HP掲載用】募集要項
@okoysm 大変申し訳ないんですが、こんな感じの内容をHPに作成いただけますか><!(ブランチとかで作成いただければ内容レビューいたします！）

Geek Women Japanでは共催コミュニティを募集いたします。
～なんかいい感じの文章をはさむ～

### 目的

①Geek Women Japan カンファレンスイベントを盛り上げる  
②Geek Women Japanのイベントを楽しくするためのサポートをいただくため    

### 共催コミュニティにお願いしたい事

①イベントの告知業のお手伝い  
共催コミュニティ内へ今後カンファレンスイベントの告知やその他Geek Women Japanが主催するコミュニティイベントの告知をお願いします。告知先の例としては以下があげられます（どれか一部でも構いません)。
- HP
- Twitter
- Facebookグループ
- メーリングリスト
- Google+

②Geek Women Japan カンファレンスでの登壇
第一回Geek Women Japanカンファレンスでは複数共催コミュニティのコラボセッションをお願いする予定です。具体的には2～3コミュニティで90分1枠のセッション時間をお渡しいたします。セッション内容は、LT・パネルディスカッション・ショートセッション・ハンズオンなど自由に選択・アレンジしてください。セッションの準備が難しい共催コミュニティにはポスターセッションをお願いいたします。    

### 共催コミュニティ特典(Geek Women Japanができること)

共催コミュニティは以下をGeek Women Japanに依頼することができます。    

①イベントの告知依頼  
コミュニティのイベントがある場合、Geek Women Japanのメールアドレス宛にイベントURLと告知用文章をいただければ、以下Geek Women Japanの保持するSNSにてイベントの告知を行います。
- Twitter
- Facebookグループ

②Geek Women Japan カンファレンス内でのコミュニティ紹介
Geek Women Japan カンファレンスのパンフレットもしくはコミュニティ紹介LTなど(詳細未定)でコミュニティの紹介を行うことができます。ぜひ女性エンジニアが集まるこの機会に知名度を上げてコミュニティの発展へお役立てください！    

③その他ご相談大歓迎  
その他「こんなことできませんか」というご相談は随時御受けいたします。 Geek Women Japanでできることであれば何事にも尽力させていただきますのでぜひご相談ください。

皆様のご参加お待ちしております
～応募フォームへのURL～

**Comment by okohs** [comment]
@mahya8585 了解！
FormのURL: https://docs.google.com/forms/d/1xzYhIZty6sSYj0bSgNt5REYX36Q5A4NEk_thfEU7bA4/viewform

**Comment by mahya8585** [comment]
wikiに上記フォームのURLを転記した。
https://github.com/GeekWomenJapan/CoreCastWorks/wiki/%E6%B1%BA%E3%81%BE%E3%81%A3%E3%81%9F%E3%81%93%E3%81%A8

**Comment by mahya8585** [comment]
公開済み。
