### ISSUE TITLE
スポンサー集め

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#6]
賛同してくれるスポンサーさんを集める

**Comment by mamix1116** [comment]
- スポンサー候補をリストアップ

**Comment by mahya8585** [comment]
3月末までに第一弾スポンサー完了したい(願望)

**Comment by okohs** [comment]
コミュニティスポンサーとカンファレンススポンサーを集めよう！

**Comment by okohs** [comment]
呼びかける順番要検討。。

**Comment by mamix1116** [comment]
・GW中、資料作成
・企業さん、まーやさんと日程調整、５月中。

**Comment by okohs** [comment]
託児所スポンサーくらいは欲しい

**Comment by okohs** [comment]
みんなで分担しようね

**Comment by mahya8585** [comment]
分担表作成済み
github即

**Comment by mahya8585** [comment]
スタートしているのでいったん完了とします。
細かい進捗についてはスプレッドシードで。
