### ISSUE TITLE
ロゴの入れ替え作業(WEB)

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#60]
- [x] facebook
- [x] twitter
- [x] HP
- [x] dots
- [x] slideshare
- [x] gmail

**Comment by okohs** [comment]
やりますー！

**Comment by okohs** [comment]
aiくださいー><
後ろ真っ白か最初のクリームにしたい！どうだろ？

**Comment by okohs** [comment]
@mahya8585 SlideShareでログインしようとしたら「そのユーザーは登録されていません（意訳）」された・・・

**Comment by mahya8585** [comment]
アカウントID geekwomenjapan でだったら入れるかね？

**Comment by okohs** [comment]
試してみる！

**Comment by okohs** [comment]
ログインできた！メールアドレスが間違ってた（geekwomen.japan@gmail.comになってた。)

**Comment by okohs** [comment]
HPについてはとりあえずiconだけ変更したよ！
