### ISSUE TITLE
ステッカー作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#61]
DEGITA
- UVステッカー印刷
- 透明PET
- 耐水フィルム
- ホワイトインクあり
- 300枚

**Comment by mahya8585** [comment]
6月中に発注予定

**Comment by mahya8585** [comment]
https://www.digitaprint.jp/forum.php

こんなかんじで型抜きをしたいがaiを持っていなかった・・・カットラインレイヤー作ってくださる方募集・・・

**Comment by okohs** [comment]
aiあるぜ

**Comment by mahya8585** [comment]
やれそうならおねがいしたく・・・！
2-3ミリの白枠ができる感じにカットラインをつけてほしい

**Comment by okohs** [comment]
まみさん助けて

**Comment by mamix1116** [comment]
カットラインを入れる。やる。2mmのカットライン。

**Comment by okohs** [comment]
https://drive.google.com/drive/u/0/folders/0B2jun1de3VScOFpuOG9yOXdBQTA
お願いします！

**Comment by mamix1116** [comment]
https://drive.google.com/drive/u/0/folders/0B8MBrPe8ha1Eam1Yc0h2TkJrSGc
保存した。
50mm×50mm
Mac イラレCS5で作成

**Comment by mahya8585** [comment]
発注前入稿チェック中。
先方からOKがで次第印刷はいってくれるはず

**Comment by mahya8585** [comment]
# 

# 《ご注文の印刷物》

［納　期］ 7営業日
［お支払方法］クレジットカード
［名　称］フィルム素材ステッカー(耐水)／白塩ビ
［お客様管理用名称］名称未設定
［色　数］フルカラー
［サイズ］28平方センチ以内
［オプション加工］強粘着/ 光沢PETラミネート/ 40パス以内/ １枚四角カット

## ［枚　数］300枚

## ●単品計　　　　　11,258 円

**Comment by okohs** [comment]
8/30〜9/3にまあやんの家に届く予定！！！

**Comment by mahya8585** [comment]
実サイズがじゃっかん小さめだったので、値段が下がりました〜

# 実会計

# 《ご注文の印刷物》

［納　期］7営業日
［お支払方法］クレジットカード
［名　称］フィルム素材ステッカー(耐水)／白塩ビ
［お客様管理名称］GeekWomenJapan
［色　数］フルカラー
［サイズ］24平方センチ以内
［オプション加工］強粘着/ 光沢PETラミネート/ 40パス以内/ １枚四角カット
［枚　数］300枚

---

 ●単品計　　　　　10,211円

---

GWJゆうちょから納品代いただきます。
