### ISSUE TITLE
カンファレンスカードの作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#62]
日程・場所決まり次第
100枚～200枚くらい

**Comment by okohs** [comment]
ラクスル片面カラーの名刺印刷で良さそう
(http://raksul.com/businesscard/standard/matte_normal_4c0c/?amount=1)

**Comment by okohs** [comment]
- ロゴ
- タイトル
- 開催日時
- 開催場所
- 連絡先
- イベントページのURL

**Comment by mamix1116** [comment]
名刺サイズに、ロゴ、タイトル、開催日、場所、URL、連絡先を片面に
入稿までやる。

**Comment by okohs** [comment]
今回は時間も時間なのでもう作りません。
