### ISSUE TITLE
コミュニティ宛メールレビュー

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#69]

**Comment by mahya8585** [comment]
- [ ] スポンサー宛のメールはビジネスメールなのでしっかりする必要がありますが、コミュニティ宛は共催＝ナカーマなので、硬いメールよりもフレンドリーなメールの方が望ましいです
- [ ] 登壇(コラボセッション)枠参加希望なのか、ポスターセッション枠希望なのかを聞いてください
- [ ] 託児スペース〜のくだり告知の時にお願いするべき内容なのでコミュニティに送る内容ではないかと思います。今回は以下を伝えるメールとするのがいいと思います
  - 参加してくれてありがとう
  - 一緒に良いカンファレンス作りましょう
  - 今回参加している共催コミュニティの一覧
  - 当日は何をやってくれますか
  - 間も無く告知サイトがオープンするので告知をお願いします
  - もう各コミュニティで告知始めちゃってください
- [ ] 「基本的な参加費は無料」は伝えて良いのですが、託児無料についてはこれも今後告知依頼をするときにお願いすればいいのでここではいらないかと思います。

**Comment by omame1986** [comment]
下書きに「GeekWomenJapanコミュニティにご参加ありがとうございます」
というタイトルで作成しました
・託児の話削除
・登壇 or ポスター どっち質問追加
・参加してくれてありがとうから、もう告知始めちゃってくださいまで、皆ナカーマ感を出すように頑張って記載

ということでレビューお願いします。

**Comment by mahya8585** [comment]
- 最後にスタッフ署名をいれる
- Happyデジタルの削除
- ところどころ微々たる文章修正

しました。
これで早速送ってしまってください！

@omame1986

**Comment by mahya8585** [comment]
これおわったな。
