### ISSUE TITLE
カンファレンスようのページを作る

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#71]

**Comment by omame1986** [comment]
イベント参加募集ページ

**Comment by okohs** [comment]
とりあえずある。タイムテーブルとか決まったスポンサーを追加次第公開しちゃう
http://geekwomenjapan.github.io/conference2016/index.html

**Comment by okohs** [comment]
タイムテーブルまで追加したので一旦クローズ。別途スポンサーの画像が揃ったら随時追加
http://geekwomenjapan.github.io/conference2016/
