### ISSUE TITLE
2016/09/15 スタッフMTG

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#73]
## Agenda
- [x] ぎょりさんにコアスタッフ説明
  - [x] Geek Women Japan趣旨
  - [x] Geek Women Japan 2016 趣旨
  - [x] 運営ツール諸々紹介と運用方法
  - [x] Geek Women Japan 2016 進捗
- [x] issue棚卸
- [x] 主担当決め
  - スポンサー連絡・共催費やりとり
  - 共催コミュニティのブリッジ役
  - 当日ボランティアスタッフのブリッジ役
  - 託児手配(まみさんから引き継ぎ＆見積もり・契約～当日まで）
  - 懇親会手配(参加者確認・会場抑え・予約～当日まで）
  - Wifiレンタル手配(見積もり・予約～当日まで）
  - 全会計総統
  - イベントページ作成/改修
  - SNS
    - 全員（あと10倍集めたいんだけどどうしたらいいだろう・・・）
- [x] タイムスケジュール決定
  会場の予約時間加味してGoogleドライブ上に時間割組みましょう  
  本項目では枠組みだけ    
- [x] コラボコミュニティ組み合わせ決定
- [x] 各種発表時間決定
  アンカンファレンスの時間が決まったら告知を流そう  
  発表者の人数もなんとなく把握したいので、把握できる方法を考える     
- [x] その他当日必要な資材（レンタル含む）を洗い出し
  どんな細かいものでもいいので（ペンとか）全部洗い出したい -> issue化

**Comment by okohs** [comment]
- スポンサー連絡・共催費やりとり→ @mahya8585 @kanakogohzu 
- 共催コミュニティのブリッジ役→ @okoysm @kanakogohzu @kabi
- 当日ボランティアスタッフのブリッジ役→ @okoysm @kanakogohzu 
- 託児手配(まみさんから引き継ぎ＆見積もり・契約～当日まで） → @omame1986 @Gyori 
- 懇親会手配(参加者確認・会場抑え・予約～当日まで）→ @omame1986 @Gyori 
- Wifiレンタル手配(見積もり・予約～当日まで）→ @omame1986 @Gyori 
- 全会計総統 → @mahya8585 
- イベントページ作成/改修→@okoysm
- SNS→全員

**Comment by Gyori** [comment]
> その他当日必要な資材（レンタル含む）を洗い出し
> どんな細かいものでもいいので（ペンとか）全部洗い出したい -> issue化

https://github.com/GeekWomenJapan/CoreCastWorks/issues/75

**Comment by Gyori** [comment]
- 託児手配(まみさんから引き継ぎ＆見積もり・契約～当日まで） →  @Gyori windows女子部に聞いてみる
- 懇親会手配(参加者確認・会場抑え・予約～当日まで）→ @omame1986 
- Wifiレンタル手配(見積もり・予約～当日まで）→ @Gyori soracomに聞いてみる
