### ISSUE TITLE
必要な資材（レンタル含む）を洗い出し

### ISSUE THREAD

**Issue by Gyori** [GeekWomenJapan/CoreCastWorks#75]
細かいもの（ペンなど）含めて洗い出す

**Comment by Gyori** [comment]
- [ ] 案内板みたいなやつ（会場入口とかに貼るやつ @OPST組
- [ ] 電源タップ  
  - クォーツとしてOPSTを追加？できるか確認する
-  PocketWiFi
  - [ ] @okoysm 3つ
  - [ ] @Gyori 3つ
  - [ ] @omame1986 3つ
- [ ] ネームタグ  @kanakogohzu 
- [x] 養生テープ（あると何かと便利 @OPST組
- [x] マッキー（あると何かと便利 @OPST組
- [x] ホッチキス（あると何かと便利 @OPST組
- [ ] 会場ごとに貼るタイムテーブル @kanakogohzu 
- [ ] 受付で配る会場・タイムテーブル案内資料 @okoysm

**Comment by mahya8585** [comment]
- [x] ネームタグ書くようのペン @OPST組
- [ ] ステッカー @OPST組
- [ ] Geek Womenの財布 @okoysm

**Comment by okoysm** [comment]
当日の連絡手段で必要じゃない？→Slackに当日の運営窓作るのでそこでやりとりする。
メンション必須。
他にない？ない？ない？？？

**Comment by okohs** [comment]
- [x] セロハンテープ @OPST組

**Comment by mahya8585** [comment]
- [ ] 受け付け用 dots受付ページQRコード(A4 *4) @OPST組

**Comment by okohs** [comment]
- [ ] Room A, B, C, D, E.託児,お手洗いはこちらみたいなroomへの案内の張り紙 *4枚 (A3〜A2, A1) @OPST組

**Comment by mahya8585** [comment]
- [x] 受付用ふせん(PC入力時間かかるので、ふせんで番号をメモる。暇な時間に入力)
- [ ] タイムボード×部屋分 (10分前、5分前、1分前、終わり） A4 @ OPST組

**Comment by mahya8585** [comment]
https://github.com/GeekWomenJapan/CoreCastWorks/issues/20#issuecomment-256859360
託児同意書の印刷何枚か
@OPST組

**Comment by mahya8585** [comment]
- Paypalさんノベルティ ＠OPST組
  - [ ] エコバック
  - [ ] ステッカー
  - [ ] 缶バッチ
- [ ] Tmixさんチラシ @OPST組
- [ ] スタッフTシャツ @kanakogohzu 
- [ ] アストロ君人形 @OPST組

**Comment by okohs** [comment]
- [ ] Instagram風フォトフレーム @okoysm

**Comment by okohs** [comment]
- [ ] 外の誘導担当向けホカロン @omame1986

**Comment by okohs** [comment]
- [ ] 手持ちベル @okoysm

**Comment by okohs** [comment]
- [x] ゴミ袋 @OPST組

**Comment by okohs** [comment]
お疲れ様！！！
