### ISSUE TITLE
コミュニティにペア発表を行う

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#78]
- メールで
- [x] ペアの発表
- [x] 相手コミュニティの連絡先
- [x] 各自で連絡とって内容の決定と準備を進めてくださいの旨を記載

**Comment by omame1986** [comment]
- [x] Java女子部
- [x] RailsGirls Japan
- [x] Windows女子部
- [x] Japan SoftLayer Girls Group / Bluemix Girls Group
- [x] GTUG Girls
- [x] JAWS-UG クラウド女子会
- [x]  Women Who Codes Japan
- [x] Django Girls Japan
- [x] dots.女子部
- [x] Ladies that UX Tokyo
