### ISSUE TITLE
ごっちさんスタッフ登録作業

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#79]
- [x] GitHub オーガナイザマスタ権限付与
- [x]  facebookページ管理者権限付与
- [x]  Twitter/gmailアドレスとパスワードの共有
- [ ]  コアキャスト作業案内
- [x]  Slackへinvite
- [ ]  現在の進捗共有
- [x]  dots.オーナー権限付与
- [x] googleDrive

**Comment by Gyori** [comment]
@okoysm すません、twitter/gmailアドレスパスワードどこにあるか見失ってしまったのでヘルプみぃです。

**Comment by Gyori** [comment]
一旦closeにします！わからんことあったらまたslackで！
