### ISSUE TITLE
見積書・請求書のテンプレート作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#81]
## ゴール

スポンサー用見積もり書・請求書のテンプレートを作成する

テンプレート見本をGoogleDriveに置きました。参考にしてください。
Corecast>スポンサー＆コミュニティ>請求書・見積書

**Comment by kanakogohzu** [comment]
作成してみたので一度ご確認お願いします 🙏 
へんてこな箇所はどんどん変えてください 🙇

**Comment by mahya8585** [comment]
![LGTM](https://lgtm.in/p/KTCIxZ3gq)

私の本名と会社住所いれました。
消費税についてはまだ聞けてないんですが、記載が必要な場合は税込み15万とかにしましょう～（今は外税扱いになってますが）
