### ISSUE TITLE
keynote用通訳・同時翻訳者手配

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#82]
前はキョンちゃんがやる！って言ってくれた。これるか確認。

コアキャストだとカビちゃんとなほさんあたりがいけそう。聞いてみる。

**Comment by okohs** [comment]
キョンちゃんに連絡中

**Comment by okohs** [comment]
キョンちゃん→11/3に出張を調整ちゅう、決まったら（月曜日中って言ってた）連絡くれる。

**Comment by okohs** [comment]
キョンちゃんだめだった。引き続き当たる。
ぎょりさんの旦那さんがイケル口なので保険。ありがたい。

**Comment by Gyori** [comment]
すんません、旦那に確認したら、GitHubにそこまで詳しくないから厳しいと思う・・って。代わりに写真係とかはやってくれそうです。
もう1人、JAWSUG繋がりのアメリカ人（日本在住、バイリンガル、エンジニア）にも聞いてみたんですが、Keynoteセッションとなると難しい、、とのこと。。
もちょい私も知り合いあたってみますー

**Comment by mahya8585** [comment]
yuryuさんに頼んでみたらどうだろうという案がPyLadiesの中で発生。
連絡を入れてみよう

**Comment by okohs** [comment]
カビちゃんかなほさんにお願いしよう。なほさんお願い中

**Comment by okohs** [comment]
メモ：yuryuさんには結局頼んでいない

**Comment by mahya8585** [comment]
なほさんOKでました。
クローズします
