### ISSUE TITLE
カンファレンスページ情報を追加する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#84]
以下を追加する
- [x] タイムスケジュール
- [x] スポンサー一覧
- [x] セッション概要一覧

**Comment by okohs** [comment]
共催コミュニティの一覧はspeaker枠で追加した。  
http://geekwomenjapan.github.io/conference2016/

**Comment by okohs** [comment]
タイムスケジュールはdotsのページは書かない。メンテがめんどい。

**Comment by okohs** [comment]
スポンサー一覧→ロゴもらったら適宜追加。
セッション概要→随時追加。コミュニティのケツを叩く
