### ISSUE TITLE
ボランティアスタッフの役割分担・MTG

### ISSUE THREAD

**Issue by okohs** [GeekWomenJapan/CoreCastWorks#85]
- [x] 調整さん立てる
- [x] 役割分担する

**Comment by okohs** [comment]
まあやんの友達「もんちゃん」が追加になったので、まあやんがフォームのリンクを送る
https://docs.google.com/forms/d/e/1FAIpQLSeFVOPSYlK63Rb7Wtn8xv9ZY0mXGANE7sQzt5aZWzhdBSOuHA/viewform

**Comment by okohs** [comment]
10/24 19:00〜21:00でMTGを行う。お知らせメールdone.

**Comment by mahya8585** [comment]
参加登録してるか確認してください～

**Comment by okohs** [comment]
役割分担done
