### ISSUE TITLE
サーバワークスロゴ掲載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#86]
※本チケットは #84 の子タスクです
## ゴール
- [x] カンファレンスページにサーバーワークスのスポンサー表示を行うこと
- [x] Googleドライブにスポンサーロゴのpngファイルを保存すること
## 記載内容
- スポンサータイプ
  - Emerald 
- 会社名
  - 株式会社サーバーワークス
- ロゴ
  - Corecast > スポンサー＆コミュニティ > スポンサーロゴ > serverworkes_logo.ai
  - **ドライブ内にpngデータ変換バージョンを保存しておいてください**

**Comment by okohs** [comment]
追加した https://github.com/GeekWomenJapan/geekwomenjapan.github.io/commit/068765d9f78003a1b7729d1402e88cdeabaab029_
