### ISSUE TITLE
サーバワークス用見積もり・請求書の作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#87]
## ゴール

サーバワークス用の以下文書の作成を行う
- [x] 見積書
- [x] 請求書
## 留意事項

とりあえず消費税部分については無記載でおねがいします。

作成： @kanakogohzu 
最終調整＆送付： @mahya8585

**Comment by mahya8585** [comment]
確定申告している人なら別だけど、そうでないなら「使い切れば」特に消費税の納税は不要とのこと。
ので、
**`税込価格3万`** で見積もり・請求を発行してください。
名前も私の名前のままでOKです

**Comment by kanakogohzu** [comment]
以下に格納しました 🍣 
GeekwomenJapan>CoreCast>スポンサー＆コミュニティ>請求書・見積書

**Comment by mahya8585** [comment]
送付済み
