### ISSUE TITLE
PayPalのHP掲載

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#88]
※ 本チケットは #84 の子タスクです
## ゴール

カンファレンスページにスポンサー情報を掲載する
## 内容
- スポンサータイプ
  - エメラルド
- 正式名称
  - PayPal Pte. Ltd. Tokyo Branch
- ロゴ
  - スポンサー＆コミュニティ>スポンサーロゴ

**Comment by okohs** [comment]
追加しました https://github.com/GeekWomenJapan/geekwomenjapan.github.io/commit/068765d9f78003a1b7729d1402e88cdeabaab029
