### ISSUE TITLE
スポンサー向けの資料を作る

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#9]

**Comment by mahya8585** [comment]
スポンサーメリットは以下どれかできる
- パネルセッション
- ブース
- 資料配布
- ブースエリアでのランチタイムLT

物スポンサーとかもあり
- フードスポンサー
- キーノートスポンサー
- サンプル配布
- 託児スポンサー

**Comment by mahya8585** [comment]
@mamix1116 資料のたたきができているとのことでしたので、リンクここにくださいな～

**Comment by mamix1116** [comment]
会場、日にちなどいれて、一旦Ver.1完成させる！

**Comment by okohs** [comment]
スポンサー目標30万

**Comment by okohs** [comment]
会場費->128,600円

**Comment by mamix1116** [comment]
会場１0万
託児20万
Wifiは登壇者用にポケファイ

**Comment by okohs** [comment]
スポンサー目標30万余裕みて40万欲しい

**Comment by mamix1116** [comment]
スポンサーブース４つ

**Comment by okohs** [comment]
一旦しょこがやる

**Comment by okohs** [comment]
[Geek Women Japan 2016協賛のお願い.pdf](https://github.com/GeekWomenJapan/CoreCastWorks/files/441976/Geek.Women.Japan.2016.pdf)

とりあえずザーッと作った

**Comment by mahya8585** [comment]
- 実績の表は良いと思うんだけど、文章の中に数値をもう少し入れると説得力が上がると思います。  
  e.g.  

```
2015年10月発足以降、主催イベント2つ、イベント補助1つの計3つのイベントを運営・運営補助いたしました。
全イベントを通じて、女性エンジニアを中心に、様々な業界・業種の女性が参加されました。 
GeekWomenJapanは共催コミュニティ制度（後述参照）をとっており、
様々な女性エンジニアコミュニティと提携・協力をして各種イベントを行っています。
この成果もあり、オフラインイベントについては
2週間の集客期間で100人規模のイベントを開催できるネットワークを確保しております。
```
- 「Geek Women Japanが主催する女性エンジニアの集まるカンファレンスです。今年が初めての
  開催です。」
  - 今年が初めての開催となります
- 「共催コミュニティには、本カンファレンスの告知や当日のスタッフ等をお手伝いしてもらう予定」
  - 今年は共催コミュニティに登壇いただく旨も追記しましょう～
- 金額についてはこちらからテーブルを用意しましょう
  - 別途slack/issueで相談
- スポンサーメリットなんですが、会場と見合ってないような気がするので、次にあげるレベルにとどめておきませんか(要相談)
  - ブース(先着順)
  - 資料配布
  - ノベルティ配布
  - HP/イベントサイトでのロゴ表示
  - スポンサーLT（先着順)
    - 部屋内での飲食ができなかった気がするので（要確認）ランチタイムと記述しておくのはやめておこう

**Comment by okohs** [comment]
レビューありがとう！修正してみました。
[Geek Women Japan 2016協賛のお願い.pdf](https://github.com/GeekWomenJapan/CoreCastWorks/files/449439/Geek.Women.Japan.2016.pdf)

**Comment by mahya8585** [comment]
だいたいOKと思います！
共催コミュニティにdotsいれてねｗ

スポンサーテーブルについて協議するMTｇしよう

**Comment by okohs** [comment]
忘れてたwww追加する！ww
