### ISSUE TITLE
github用見積もり・請求書作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#91]
## ゴール

github用の以下文書の作成を行う
- [x] 見積書
- [x] 請求書
## 留意事項

税込み価格で記載
- GitHub Japan
- Saphire(だが3万で切ってください）

作成： @kanakogohzu 
最終調整＆送付： @mahya8585

**Comment by kanakogohzu** [comment]
作成し以下の場所に格納しておきました 😃  ご確認をお願い致します 🙏 
GeekwomenJapan>CoreCast>スポンサー＆コミュニティ>請求書・見積書

**Comment by mahya8585** [comment]
送付済み
