### ISSUE TITLE
ビジネスブレイン太田昭和用見積書・請求書作成

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#92]
## ゴール

ビジネスブレイン太田昭和用の以下文書の作成を行う
- [x] 見積書
- [x] 請求書
## 留意事項

税込み価格で記載
- 株式会社ビジネスブレイン太田昭和
- サファイア

作成： @kanakogohzu 
最終調整＆送付： @mahya8585

**Comment by kanakogohzu** [comment]
以下に格納しておきました :tipping_hand_man: 
GeekwomenJapan>CoreCast>スポンサー＆コミュニティ>請求書・見積書

よろしくお願いします :bowing_woman:

**Comment by mahya8585** [comment]
送付済み
