### ISSUE TITLE
New Years Party 2017

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#97]
MSでやれそう

13日で打診

10-18日の間で調整

**Comment by mahya8585** [comment]
MSから「条件付き」の連絡あり。詳細なし。
折り返しのメールを送る

**Comment by mahya8585** [comment]
2月にMSでイベントを企画しているのでGeek Womenのイベント名でやってもいい？
の連絡あり。
先方の温度感含め、来週(24日週)OPStでMTGします。昼間ですが参加したい方はご連絡ください。

方向的には
- 運営手伝いOk
- 名前は開催内容による
- 何がともあれNew Years Partyは別途やる

の方向で進めたいと思います

**Comment by mahya8585** [comment]
http://gloops.com/company/profile/
gloopsさんのおしゃれ会場を借りれることになりました。

**Comment by mahya8585** [comment]
1月13日に決定

@okoysm @Gyori @kanakogohzu @omame1986  @mamix1116 
どなたかイベントページの作成を・・・

**Comment by okohs** [comment]
@mahya8585 今作成している。
今とりあえず一般参加枠とスタッフ枠だけでいいかな？
あと人数は去年dots.でやったときと一旦揃える

**Comment by mahya8585** [comment]
ありがとうー！
 LT枠と一般枠、スタッフ枠でお願いできますか。
人数は2016と一緒でとりあえずおけです

**Comment by mahya8585** [comment]
18時の来訪お待ちしております。
5階につきましたら、電話をいただければお迎えに伺います。

マイクはハンドマイク3本、ピンマイク1本の用意があります。
接続端子は、HDMIとVGAの2種類ございます。
16:9だったと思います。

飲食OKです。
