### ISSUE TITLE
カンファレンスページとdotsページにランチ情報を公開する

### ISSUE THREAD

**Issue by mahya8585** [GeekWomenJapan/CoreCastWorks#99]
Javaチャンピオンのskrbさんが参宮橋近辺のランチ情報をマップ化してくださいました！
(おすすめ情報つき！)
https://www.google.com/maps/d/u/0/viewer?hl=ja&authuser=0&mid=1h7XJToBfqEWG3vhzYNdAZCwGAZQ

ランチが外部になるので、カンファレンスページとdotsページにリンク追加しましょう～
- [x] カンファレンスページ： @okoysm 
- [x] dotsページ： @Gyori 

よろしくおねがいします

**Comment by Gyori** [comment]
完了です！
